-- =============================================
-- All Iron Sports — Club Migration v2
-- Datos curados con ligas correctas
-- =============================================

-- PASO 1: Eliminar entradas basura
DELETE FROM clubs WHERE name IN ('Free Agent', 'Intermediary', 'Agent', 'AGENT', 'Investor', 'Unemployed', 'Unknown', 'TBD', '4SportAgency', 'Ludonautics', 'Global Football Holdings', 'Luis Campos', 'Ares Management', 'Zelus', '11Hacks', 'FC Förderkader', 'Kuwait/ QATAR/ EGPYT', 'UAE LEAGUE', 'USL LEAGUE', 'ITALY', 'Austria NT', 'Hungary NT', 'Chile NT', 'Ecuador FA', 'AUF', 'US NT', 'Ukraine U21', 'France Women', 'Yusuke Imai');

-- PASO 2: Corregir clubes escoceses mal asignados
UPDATE clubs SET country='Scotland', league='Scottish Premiership'
WHERE name IN ('Aberdeen', 'Celtic', 'Rangers', 'Heart of Midlothian', 'Hearts', 'Hibernian', 'Kilmarnock', 'Livingston', 'Motherwell', 'St Mirren', 'St Johnstone', 'Dundee', 'Dundee United', 'Ross County', 'Hamilton Academical', 'Inverness CT', 'Partick Thistle', 'Ayr United', 'Dundee FC') AND (country IS NULL OR country != 'Scotland');

-- PASO 3: Mover clubes holandeses de Eredivisie → Eerste Divisie
UPDATE clubs SET league='Eerste Divisie'
WHERE name IN ('Excelsior', 'FC Volendam', 'Cambuur', 'Roda JC', 'De Graafschap', 'FC Eindhoven', 'Jong Ajax', 'Jong PSV', 'Jong AZ', 'Jong Utrecht', 'Helmond Sport', 'MVV Maastricht', 'Telstar', 'Top Oss', 'VVV-Venlo') AND league='Eredivisie';

-- PASO 4: Mover clubes belgas de Pro League → 1B Pro League
UPDATE clubs SET league='1B Pro League'
WHERE name IN ('Lommel SK', 'KV Oostende', 'Zulte Waregem', 'Eupen', 'KMSK Deinze', 'Beveeren') AND league='Pro League';

-- PASO 5: Insertar todos los clubes (skip si ya existen)
INSERT INTO clubs (id, name, country, league, is_priority, needs, created_at)
VALUES
  (gen_random_uuid(), 'Aberdeen', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Celtic', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rangers', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Heart of Midlothian', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hibernian', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kilmarnock', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Livingston', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Motherwell', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'St Mirren', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'St Johnstone', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dundee', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dundee United', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ross County', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hamilton Academical', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Inverness CT', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Partick Thistle', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ayr United', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dundee FC', 'Scotland', 'Scottish Premiership', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Olympiakos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Panathinaikos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AEK Athens', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'PAOK', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aris Thessaloniki', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atromitos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Asteras Tripolis', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'OFI Creta', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'PAS Giannina', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Panetolikos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AE Larissa', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Levadiakos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AO Egaleo', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Panseraikos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aiolis Eolikos', 'Greece', 'Super League Greece', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Anorthosis', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Apoel FC', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pafos FC', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AEK Larnaca', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Omonia Nicosia', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AEL Limassol', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aris Limassol', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Karmiotissa', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nea Salamina', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Apollon Limassol', 'Cyprus', 'First Division Cyprus', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Hilal', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Nassr', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Ittihad', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Ahli', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Fateh', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Faisaly', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Shabab', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Wahda', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Hazem', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Riyadh', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Tai', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Qadsiyah', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Batin', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Jabalain', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Abha', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ohod Club', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Damac FC', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Akhdoud', 'Saudi Arabia', 'Saudi Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Sadd', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Duhail', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Rayyan', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Gharafa', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Wakrah', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Arabi', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Umm Salal', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Muaither SC', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Ahly Doha', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Khor', 'Qatar', 'Qatar Stars League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Ain FC', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Wasl', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sharjah FC', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Wahda Abu Dhabi', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Baniyas', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Al Nasr Dubai', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hatta FC', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ajman Club', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Emirates FC', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KhorFakkan', 'UAE', 'Arabian Gulf League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Milan', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atalanta', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bologna', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cagliari', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Como', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Empoli', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fiorentina', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Genoa', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hellas Verona', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Inter Milan', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Juventus', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SS Lazio', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'US Lecce', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Monza', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SSC Napoli', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Parma', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AS Roma', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Torino FC', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Udinese', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Venezia FC', 'Italy', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ascoli', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bari', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brescia', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Catanzaro', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cesena', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cittadella', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cosenza', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cremonese', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Frosinone', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mantova', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Modena', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Palermo', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pisa', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SPAL', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sampdoria', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Salernitana', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Spezia', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sudtirol', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ternana', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Carrarese', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Reggiana', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Juve Stabia', 'Italy', 'Serie B', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Avellino', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Benevento', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Catania', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Crotone', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Foggia', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Giugliano', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lecco', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lucchese', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pescara', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Potenza', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Taranto', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Triestina', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Turris', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Virtus Entella', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Trapani', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Torres', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rimini', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pianese', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pineto', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Perugia', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Padova', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pro Vercelli', 'Italy', 'Serie C', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Arsenal', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aston Villa', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brentford', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brighton', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Chelsea', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Crystal Palace', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Everton', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fulham', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ipswich Town', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Leicester City', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Liverpool', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Manchester City', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Manchester United', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Newcastle United', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nottingham Forest', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Southampton', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tottenham Hotspur', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'West Ham United', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wolverhampton Wanderers', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AFC Bournemouth', 'England', 'Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Blackburn Rovers', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Blackpool', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bristol City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Burnley', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cardiff City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Coventry City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Derby County', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hull City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Leeds United', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Luton Town', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Middlesbrough', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Millwall', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Norwich City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Oxford United', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Plymouth Argyle', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Portsmouth', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Preston North End', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'QPR', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sheffield United', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sheffield Wednesday', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stoke City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sunderland', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Swansea City', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Watford', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'West Bromwich Albion', 'England', 'EFL Championship', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Barnsley', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Birmingham City', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bolton Wanderers', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bradford City', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cambridge United', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Charlton Athletic', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Exeter City', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fleetwood Town', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Huddersfield Town', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lincoln City', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Northampton Town', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Peterborough United', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Reading', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rotherham United', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Shrewsbury Town', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stevenage', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stockport County', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wigan Athletic', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wycombe Wanderers', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Burton Albion', 'England', 'EFL League One', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bristol Rovers', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Carlisle United', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cheltenham', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Crewe Alexandra', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Doncaster Rovers', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gillingham', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Grimsby Town', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Harrogate Town', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Leyton Orient', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mansfield Town', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Morecambe', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Newport County', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Port Vale', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Salford City', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Swindon Town', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tranmere Rovers', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Walsall', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wrexham', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'York City', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Colchester United', 'England', 'EFL League Two', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Athletic Club', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atletico Madrid', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Barcelona', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Betis', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Celta', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Espanyol', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Getafe', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Girona', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Las Palmas', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Leganes', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mallorca', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Osasuna', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rayo Vallecano', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Madrid', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Sociedad', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sevilla', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Valencia', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Valladolid', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Villarreal', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Deportivo Alaves', 'Spain', 'La Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Albacete', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Almeria', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Burgos CF', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Castellon', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cartagena', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cordoba CF', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eldense', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Huesca', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Levante', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lugo', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Malaga', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mirandes', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Murcia', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Oviedo', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Racing Santander', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sporting Gijon', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tenerife', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zaragoza', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Granada', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Elche', 'Spain', 'La Liga 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Alcorcon', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Andorra FC', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ceuta', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Deportivo', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eibar', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fuenlabrada', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Merida AD', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SD Ponferradina', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Racing Ferrol', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sabadell', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'UD Logrones', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'UD Ibiza', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Linares Deportivo', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Union', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'UCAM Murcia', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cultural Leonesa', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Numancia', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Andorra', 'Spain', 'Primera RFEF', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AS Monaco', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AJ Auxerre', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Angers', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brest', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lens', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lille', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lyon', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Marseille', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Metz', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Montpellier', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nantes', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nice', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'PSG', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Reims', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rennes', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Saint-Etienne', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Strasbourg', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Toulouse', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Clermont', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Le Havre', 'France', 'Ligue 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Amiens', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Ajaccio', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Caen', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Chambly', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dijon', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dunkerque', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'EA Guingamp', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Annecy', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Grenoble Foot', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Laval', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Niort', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Orleans', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pau FC', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rodez', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sochaux', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Troyes', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Valenciennes', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Paris FC', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Red Star FC', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Quevilly Rouen', 'France', 'Ligue 2', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Augsburg', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bayer Leverkusen', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bayern Munich', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bochum', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Borussia Dortmund', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Borussia Monchengladbach', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Darmstadt 98', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eintracht Frankfurt', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SC Freiburg', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Holstein Kiel', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FSV Mainz 05', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'RB Leipzig', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'St. Pauli', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'VfB Stuttgart', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'TSG Hoffenheim', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Union Berlin', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'VfL Wolfsburg', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Werder Bremen', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Heidenheim', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Koln', 'Germany', 'Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Arminia Bielefeld', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dynamo Dresden', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Ingolstadt', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Kaiserslautern', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Magdeburg', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Nurnberg', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Saarbrucken', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Schalke 04', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fortuna Dusseldorf', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hamburger SV', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hannover 96', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jahn Regensburg', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Karlsruher SC', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Osnabrück', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SC Paderborn', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ulm 1846', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sv Elversberg', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Braunschweig', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Greuther Furth', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), '1860 Munich', 'Germany', '2. Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Ingolstadt 04', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'TSV 1860 München', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SV Waldhof Mannheim', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Preußen Münster', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Erzgebirge Aue', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rot-Weiss Essen', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MSV Duisburg', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SpVgg Unterhaching', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'VfL Osnabrück', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Viktoria Köln', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Energie Cottbus', 'Germany', '3. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Benfica', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Braga', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Porto', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sporting CP', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Arouca', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Boavista', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Casa Pia', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Chaves', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Estoril', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Famalicao', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Farense', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gil Vicente', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Moreirense', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nacional', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pacos Ferreira', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Portimonense', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rio Ave', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Santa Clara', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vitoria Guimaraes', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vizela', 'Portugal', 'Primeira Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ajax', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AZ Alkmaar', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Feyenoord', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'PSV', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Utrecht', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NEC Nijmegen', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Twente', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SC Heerenveen', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sparta Rotterdam', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Almere City', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Go Ahead Eagles', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'PEC Zwolle', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'RKC Waalwijk', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NAC Breda', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fortuna Sittard', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Heracles Almelo', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Groningen', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Willem II', 'Netherlands', 'Eredivisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Excelsior', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Volendam', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cambuur', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Roda JC', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'De Graafschap', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Eindhoven', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jong Ajax', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jong PSV', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jong AZ', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jong Utrecht', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Helmond Sport', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MVV Maastricht', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Telstar', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Top Oss', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'VVV-Venlo', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Dordrecht', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Emmen', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jong Feyenoord', 'Netherlands', 'Eerste Divisie', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Club Brugge', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Anderlecht', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KAA Gent', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KRC Genk', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Union SG', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Beerschot', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cercle Brugge', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Charleroi', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KV Kortrijk', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KV Mechelen', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'OH Leuven', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sint-Truiden', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Standard Liège', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Westerlo', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'RWDM', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Deinze', 'Belgium', 'Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lommel SK', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KV Oostende', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zulte Waregem', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eupen', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KMSK Deinze', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'RFC Seraing', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SK Beveren', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Beveeren', 'Belgium', '1B Pro League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Besiktas', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fenerbahce', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Galatasaray', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Trabzonspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Basaksehir', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sivasspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Konyaspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Antalyaspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Alanyaspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kayserispor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rizespor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hatayspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gaziantep FK', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ankaragucü', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kasimpasa', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Samsunspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pendikspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eyüpspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bodrum FK', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Adana Demirspor', 'Turkey', 'Süper Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bandirmaspor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Boluspor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bursaspor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Denizlispor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Erzurumspor FK', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Genclerbirligi', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Goztepe', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Istanbulspor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Karagumruk', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Keciörengücü', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kocaelispor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Manisa FK', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sakaryaspor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Umraniyespor', 'Turkey', '1. Lig', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'CSKA Sofia', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ludogorets', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Levski Sofia', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'CSKA 1948', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slavia Sofia', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Botev Plovdiv', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cherno More', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Etar', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pirin FK', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Loko Plovdiv', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Arda Kardzhali', 'Bulgaria', 'First Professional League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Basel', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'BSC Young Boys', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Zurich', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Grasshoppers', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lausanne', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lugano', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Luzern', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Servette', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sion', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'St Gallen', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Winterthur', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Yverdon Sport', 'Switzerland', 'Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Aarau', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Thun', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Wil 1900', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Xamax', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vaduz', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Schaffhausen', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stade Lausanne-Ouchy', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Chiasso', 'Switzerland', 'Challenge League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Salzburg', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SK Sturm Graz', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SK Rapid Wien', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Austria Wien', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'LASK', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wolfsberger AC', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'TSV Hartberg', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SCR Altach', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Blau-Weiss Linz', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Grazer AK', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Klagenfurt', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SV Ried', 'Austria', 'Austrian Bundesliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Austria Lustenau', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Admira Wacker', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Juniors OÖ', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Dornbirn', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SC Austria Lustenau', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SV Ried II', 'Austria', 'Austrian 2. Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lech Poznan', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Legia Warsaw', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rakow Czestochowa', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pogon Szczecin', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cracovia', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Piast Gliwice', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wisla Krakow', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gornik Zabrze', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jagiellonia Bialystok', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slask Wroclaw', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'LKS Lodz', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Radomiak Radom', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Motor Lublin', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Wisla Plock', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zaglebie Lubin', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Warta Poznan', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Widzew Lodz', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'GKS Katowice', 'Poland', 'Ekstraklasa', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slavia Praha', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sparta Praha', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Banik Ostrava', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bohemians', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Slovacko', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mlada Boleslav', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sigma Olomouc', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jablonec', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hradec Kralove', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slovan Liberec', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pardubice', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fastav Zlin', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zbrojovka Brno', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Teplice', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dukla Praha', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MFK OKD Karvina', 'Czech Republic', '1. liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slovan Bratislava', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dunajska Streda', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MSK Zilina', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MFK Ruzomberok', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Trencin', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Vion', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SKF Sered', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MFK Zemplin Michalovce', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Spartak Trnava', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'DAC', 'Slovakia', '1. Fortuna liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FCSB', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'CFR Cluj', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rapid Bucharest', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Universitatea Craiova', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Farul Constanta', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Petrolul Ploiesti', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Otelul Galati', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sepsi', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Hermannstadt', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'UTA Arad', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dinamo Bucharest', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Botosani', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Arges', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gloria Buzau', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'U. Cluj', 'Romania', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Crvena Zvezda', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Partizan', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Cukaricki', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'TSC Backa Topola', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vojvodina', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Radnicki Nis', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Spartak Subotica', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Radnik', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Javor', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vozdovac', 'Serbia', 'Super liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dinamo Zagreb', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hajduk Split', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'HNK Rijeka', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Osijek', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Lokomotiva', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Slaven Belupo', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Varazdin', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'HNK Gorica', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Istra', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lokomotiv Zagreb', 'Croatia', 'HNL', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Maribor', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Celje', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Olimpija Ljubljana', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Domzale', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Koper', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Bravo', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NS Mura', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NK Krsko', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aluminij', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kalcer Radomlje', 'Slovenia', 'PrvaLiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ferencvaros', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MOL Fehervar', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Debreceni VSC', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Puskas Akademia', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'MTK Budapest', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pecsi MFC', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kisvarda', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Diosgyor', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Budafoki', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ujpest', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Haladas', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Eto FC', 'Hungary', 'OTP Bank Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dinamo Tblisi', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dinamo Batumi', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Dila Gori', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fc Gagra', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fc Telavi', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Samtredia', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Samgurali', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Torpedo Kutaisi', 'Georgia', 'Erovnuli Liga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Copenhagen', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Midtjylland', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brondby', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nordsjaelland', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Silkeborg', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Randers', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Odense', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Horsens', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Viborg', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aarhus GF', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'HB Koge', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vejle', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Soenderjyske', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hillerod', 'Denmark', 'Superliga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Malmö FF', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AIK', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'IFK Goteborg', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hammarby', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Djurgarden', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Elfsborg', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hacken', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kalmar FF', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sirius', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Örebro', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Degerfors', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Landskrona', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'IFK Varnamo', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ostersund', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bryne', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aalesund', 'Sweden', 'Allsvenskan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rosenborg', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bodo Glimt', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Molde', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Viking', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Brann', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lillestrom', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hamarkameratene', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Haugesund', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stromsgodset', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kristiansund', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tromso', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fredrikstad', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Odd BK', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sandefjord', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sarpsborg', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sogndal', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Stabaek', 'Norway', 'Eliteserien', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'HJK Helsinki', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Inter Turku', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'SJK', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ilves', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'KuPS', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Lahti', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Haka', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'AC Oulu', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Honka', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'HIFK', 'Finland', 'Veikkausliiga', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Maccabi Tel Aviv', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Maccabi Haifa', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Tel Aviv', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Beer Sheva', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Beitar Jerusalem', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Jerusalem', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bnei Yehuda', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Maccabi Netanya', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Haifa', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Petah Tikva', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Maccabi Petah Tikva', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hapoel Kfar Saba', 'Israel', 'Israeli Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'River Plate', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Boca Juniors', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Racing Club', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Independiente', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'San Lorenzo', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Estudiantes', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atletico Tucuman', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Talleres', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lanus', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Newells', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Defensa y Justicia', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Godoy Cruz', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Banfield', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Huracan', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Belgrano', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Colon', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gimnasia La Plata', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aldosivi', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Velez Sarfield', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Central Cordoba', 'Argentina', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Flamengo', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Palmeiras', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atletico Mineiro', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fluminense', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Corinthians', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Internacional', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Gremio', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sao Paulo', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Botafogo', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Santos', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'America Mineiro', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bahia', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bragantino', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Athletico Paranaense', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cruzeiro', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cuiaba', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fortaleza', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Goias', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Coritiba', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vasco da Gama', 'Brazil', 'Serie A', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'America', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Guadalajara', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cruz Azul', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pumas', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Monterrey', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tigres', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atlas', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Santos Laguna', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Leon', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Toluca', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atletico San Luis', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pachuca', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Necaxa', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mazatlan', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Juarez', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Puebla', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Xolos Tijuana', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cancun', 'Mexico', 'Liga MX', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atlanta United', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Austin FC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Charlotte FC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Chicago Fire', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Colorado Rapids', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Columbus Crew', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'DC United', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Cincinnati', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Dallas', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Houston Dynamo', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Inter Miami', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sporting Kansas City', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'LA Galaxy', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'LAFC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Minnesota United', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nashville SC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'New England Revolution', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'New York City FC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'New York Red Bulls', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Orlando City', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Philadelphia Union', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Portland Timbers', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Real Salt Lake', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'San Jose Earthquakes', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Seattle Sounders', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'St Louis City SC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Toronto FC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vancouver Whitecaps', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'CF Montreal', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'San Diego FC', 'USA', 'MLS', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Atletico Nacional', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Junior', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Millonarios', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'America Cali', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Deportivo Cali', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tolima', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Once Caldas', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Envigado', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'La Equidad', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Deportivo Pasto', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pereira', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aguilas Doradas', 'Colombia', 'Liga Betplay', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Colo Colo', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Universidad de Chile', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Universidad Catolica', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Huachipato', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Palestino', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cobresal', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Magallanes', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Audax Italiano', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Everton Vina', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'O Higgins', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Union Espanola', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'La Serena', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Santiago Wanderers', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Curico', 'Chile', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Alianza Lima', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Universitario', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sporting Cristal', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Melgar', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cesar Vallejo', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ayacucho FC', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Cusco FC', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'San Martin', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Sport Boys', 'Peru', 'Liga 1', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Barcelona SC', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Emelec', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Liga de Quito', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Independiente del Valle', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aucas', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Guayaquil City', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mushuc Runa', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tecnico Universitario', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Delfin', 'Ecuador', 'LigaPro', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Nacional', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Peñarol', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Defensor Sporting', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Danubio', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Boston River', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Montevideo City Torque', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Liverpool Montevideo', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rampla Juniors', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Progreso', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rentistas', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Albion', 'Uruguay', 'Primera Division', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zenit', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'CSKA Moscow', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Spartak Moscow', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dynamo Moscow', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Krasnodar', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Lokomotiv Moscow', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rostov', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Rubin Kazan', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Khimki', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Orenburg', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Pari Nizhegorodets', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Ufa', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fakel Voronezh', 'Russia', 'Premier League Russia', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dynamo Kiev', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Shakhtar Donetsk', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Vorskla Poltava', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dnipro-1', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zorya Luhansk', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kolos Kovalivka', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Dnipro', 'Ukraine', 'Ukrainian Premier League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FC Astana', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Shakhter Karaganda', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kairat', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kaysar', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Ordabasy', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Tobol', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Aktobe', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Qyzyljar', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kaspiy', 'Kazakhstan', 'Premier League Kazakhstan', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'ATK Mohun Bagan', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bengaluru FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Chennaiyin FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'East Bengal', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Goa FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hyderabad FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Jamshedpur FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Kerala Blasters', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Mumbai City', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'NorthEast United', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Odisha FC', 'India', 'Indian Super League', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Bate Borisov', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Riga', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Liepaja', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK Jelgava', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'FK RFS', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Fk Metta', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Zalgiris', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Panevezys', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Hegelmann', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now()),
  (gen_random_uuid(), 'Suduva', 'Baltics', 'Baltic Leagues', false, '[]'::jsonb, now())
ON CONFLICT (name) DO NOTHING;

-- Verificación final
SELECT country, league, COUNT(*) as clubes FROM clubs
GROUP BY country, league ORDER BY country, league;