// ── Versión de la app y novedades ────────────────────────────
// BUILD_ID lo inyecta vite en cada build (plugin build-id en vite.config.ts),
// que además emite /version.json con el mismo id. La app compara ambos
// periódicamente: si difieren, hay una versión nueva desplegada.
//
// CHANGELOG: añade una entrada arriba en cada deploy con cambios visibles.
// Tras actualizar, la home muestra "🆕 Novedades" con la última entrada
// hasta que el usuario la descarta.

export const BUILD_ID: string = typeof __BUILD_ID__ !== 'undefined' ? __BUILD_ID__ : 'dev'

export interface ChangelogEntry {
  date: string      // "YYYY-MM-DD"
  /** Novedades que ve todo el equipo en la pantalla de inicio */
  items: string[]
  /** Cambios técnicos o de administración: solo los ven los admin */
  adminItems?: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    date: '2026-10-01',
    items: [
      'Ficha del jugador → Rendimiento: la pestaña «Vídeoanálisis» pasa a ser «Análisis» y distingue cinco servicios, cada uno con su color — Sesión de videoanálisis (nos sentamos con el jugador), Vídeo (preparado expresamente para él), Recurso (un concepto táctico con material hecho para otro), Entrenamiento (sesión en campo) e Informe de datos (se le ha enviado uno). Arriba se ve cuántos lleva de cada tipo y se puede filtrar',
      'Servicios de análisis: ahora se pueden editar (lápiz), tienen título y descripción en cajas separadas, y en vez de un único encargado se marcan todas las personas del equipo que han participado. En el calendario salen a nombre de todas ellas, con el tipo de servicio delante',
      'Captación → Conclusiones: se abre directamente en el campograma en vez de en la matriz. La matriz sigue a un clic',
      'Editar jugador y Nuevo jugador: nuevo campo «Segunda nacionalidad», al lado de la primera. Si el jugador ya tenía dos escritas con una barra («Spain/Nigeria»), salen cada una en su campo',
      'Pipeline: la columna «Decidir» pasa a llamarse «Frío / no relevante». Los jugadores que estaban ahí siguen ahí; solo cambia el nombre',
      'Corregido: en Pipeline, al abrir la ficha de Captación de un jugador desde su tarjeta, la cabecera de la página tapaba la parte de arriba de la ficha (nombre y botón de cerrar) y no se podía llegar a ella. Las fichas flotantes salen ahora por encima de todo',
      'De tarea a evento: al marcar como hecha una tarea de tipo Llamada, Reunión o Visita, la app pregunta «¿qué pasó?» (en las llamadas, además, contestó / no contestó). Al aceptar, la tarea se completa y queda un evento con la fecha de hoy en el calendario, en la ficha del jugador y, si está en el pipeline, en su tarjeta. Con «Solo completar» se cierra sin dejar nada',
      'Tipos de tarea: nuevos «Llamada» y «Visita», y «Reunión/Comida» pasa a llamarse «Reunión», para que el tipo de la tarea y el del evento se llamen igual. Las tareas que ya tenías como «Reunión/Comida» se ven como «Reunión»',
      '¿Tarea o evento? Ahora es la misma ventana, y arriba se elige cuál es, con la diferencia escrita: una TAREA es algo que hay que hacer (se marca como hecha y puede vencer); un EVENTO es algo que ocurre un día, o ya ocurrió (reunión, visita, llamada, viaje…) y no se completa. En las listas, los eventos ya no llevan el círculo de «hecha»',
      'Nueva tarea, rehecha: lo primero es qué hay que hacer; después con quién está relacionada — general, un jugador nuestro o un jugador de Captación, con buscador en vez de una lista interminable —, quién la hace y para cuándo (con atajos Hoy / Mañana / Próxima semana / Sin fecha). Tipo, prioridad y repetir están a la vista, sin tener que abrir «Más opciones»',
      'Tareas de jugadores de Captación: se pueden crear desde Tareas y desde el calendario. Quedan ligadas a su ficha de scouting (el nombre en la fila la abre) y, si el jugador está en el pipeline, apuntadas en el historial de su tarjeta de Firmar',
      'Calendario → día ampliado: las tarjetas del equipo separan ahora dos cosas que antes iban mezcladas — «En curso» (en lo que está cada uno ahora: sus tareas marcadas en curso, tengan la fecha que tengan) y «Para hoy» (lo que tiene con fecha de ese día) —, con un texto que lo explica',
      'Sesiones de videoanálisis (ficha del jugador → Rendimiento): ahora se les puede poner hora, lugar y encargado, y salen en el calendario a esa hora, con el lugar y a nombre del encargado (por defecto quien la apunta, que suele ser el analista, y no el gestor del jugador). El enlace al vídeo pasa a ser opcional, para poder dejar la sesión agendada antes de tener el vídeo',
      'Corregido: un evento que apuntabas para otras personas salía a tu nombre y en tu lista. Ahora un evento es de quienes asisten, no de quien lo crea; solo si no marcas a nadie queda a tu nombre',
      'Tareas que nacen del pipeline: al abrir la tarea de una próxima acción de Firmar, debajo de los comentarios se ve el historial de la tarjeta del jugador (los últimos apuntes) y un botón «Abrir tarjeta»',
      'Viajes en el calendario: botón «Viaje» para planear una salida de varios días (destino, ida, vuelta y quién va). El viaje sale en el calendario cada uno de sus días, arriba del todo, a la vista de todo el equipo y a nombre de quienes viajan',
      'Viajes → a quién visitar: al abrir un viaje, la app sugiere los jugadores del pipeline de Firmar a los que puedes visitar — primero los que juegan en la ciudad de destino y después los del resto de la zona —, con los calientes y los que llevan más tiempo sin tocar delante. Desde cada uno puedes abrir su tarjeta o dejar la visita apuntada en un día del viaje: queda en el calendario y en el historial de su tarjeta',
      'Boulema: un informe que te han pedido y aún no has escrito sale en tu lista de Tareas como pendiente («Informe Boulema — jugador»). Al pulsarlo te lleva a Boulema, y desaparece solo cuando escribes el informe',
      'Calendario: usa todo el ancho de la pantalla (antes se quedaba en una columna central estrecha) y, en la vista Columnas, los días sin nada se encogen para dejar sitio a los que tienen cosas',
      'Videoanálisis conectado: las sesiones que apuntas en la ficha del jugador (Rendimiento → Vídeoanálisis) salen en el calendario ese día, a nombre de sus encargados. Hay un tipo de tarea nuevo, «Videoanálisis», y las tareas de ese tipo de un jugador aparecen también en su ficha, en Rendimiento → Vídeoanálisis',
      'Pipeline ⇄ Tareas: si comentas en la tarea que nació de una próxima acción de Firmar («conseguir el contacto»…), el comentario queda también en el historial de la tarjeta del jugador en el pipeline',
      'Más filtros de botones convertidos en desplegables: zona y categoría en Equipos (con la cobertura de cada una), liga en Fin de contrato, veredicto en la vista ampliada de un partido, año y posición al afinar los sugeridos de un partido, prioridad en Oportunidades, y estatus en Firmar desde el móvil',
      'Firmar: si dos personas apuntan algo en la misma tarjeta casi a la vez, ya no se pierde ninguna de las dos notas. Al guardar solo se escribe lo que has cambiado tú, sobre la versión que hay en ese momento',
      'Tareas, jugadores de Captación y partidos: al guardar solo se escribe lo que has cambiado. Antes se guardaba la ficha entera y podía llevarse por delante un cambio que otra persona acababa de hacer en otro campo (por ejemplo, activar el campograma borraba la valoración recién puesta por otro scout)',
      'Más ligero con todo el equipo conectado: cuando alguien mete un informe, mueve una tarea o toca un partido, a los demás les llega solo ese cambio, en vez de volver a descargarse la tabla entera (unos 12.000 informes por cada informe nuevo)',
      'Móvil: la barra de abajo pasa de siete botones a cinco (Tareas · Captación · Pipeline · Distribución · Más). «Más» abre Buscar y Boulema. «Tareas» lleva a la lista nueva; la pantalla «Mi día» antigua deja de estar en la barra',
      'Móvil: todo lo que flota abajo (avisos, «Sincronizando», la barra de mover vencidas, los botones «+» de Distribución, el botón de Planificación) se coloca por encima de la barra en vez de montarse sobre ella, también en iPhone. El botón de Planificación se quita mientras hay una ficha flotante abierta',
      'Móvil, Tareas: cada fila tiene un «⋯» al final que saca hecha, reprogramar, reasignar y abrir (antes reasignar solo existía con ratón). El círculo de estado es más fácil de acertar con el dedo, y deslizar desde el mismo borde de la pantalla ya no compite con el «atrás» del navegador',
      'Tareas: al marcar una tarea como hecha sale «Tarea hecha · Deshacer» durante unos segundos, por si fue sin querer',
      'Captación en el móvil: las pestañas pasan a un desplegable (antes «Partidos» y «Planificación» quedaban fuera de la pantalla). Y en Partidos, los de hoy salen los primeros, ordenados por hora',
      'Ficha de partido en el móvil: los botones campo/vídeo y «marcar visto» de cada scout son más grandes, y quitar a un scout pide confirmación (la ✕ estaba pegada y se pulsaba sin querer)',
      'Informe rápido desde la ficha de un partido (y desde su vista ampliada): si te quedas sin señal ya no se pierde. Se guarda en la cola y se envía solo cuando vuelve la conexión; y lo que vas escribiendo queda como borrador del jugador, así que si cierras la ficha lo recuperas al volver a abrir el informe',
      'Buscar (⌘K): en Mantenimiento se abrían dos buscadores a la vez. Ahora es uno solo, el mismo que en el resto de la app',
      'Abrir cosas ya no te saca de donde estás. Desde el calendario o desde Tareas, un partido abre su ficha flotante encima (la misma de Captación, con scouts, informes y alineación), y una llamada o reunión de Firmar abre la tarjeta del pipeline como panel lateral. Al cerrarlas sigues en el mismo día y con los mismos filtros',
      'Pipeline: al pulsar en la ficha de Captación de un jugador desde su tarjeta, la ficha se abre encima sin salir del pipeline',
      'Ficha de jugador y ficha de miembro del equipo: al volver atrás, la pantalla de la que venías está tal cual la dejaste — misma pestaña, mismos filtros, misma semana del calendario y a la misma altura de la página —, en vez de empezar de cero',
      'Nuevo evento → «Partido»: el partido se crea igual que desde Captación (primer scout como responsable, vídeo por defecto) y, si falla la asignación de algún scout, el partido se queda creado y se avisa, en vez de dejar el formulario abierto y arriesgarse a crearlo dos veces',
      'Partidos en el calendario y en Tareas: ya no salen tachados ni en rojo cuando pasan, porque no son tareas. Lo único que llevan es un tick verde junto a las iniciales del scout que ya ha metido su informe de ese partido',
      'Corregido: los eventos pasados (visitas, reuniones, comidas…) salían tachados y como «hecha», como si fueran tareas. Un evento no se completa ni vence: ahora se ve siempre normal, y en el recuento del día va aparte de las tareas',
      'Nuevo evento → tipo «Partido»: ya no crea un evento suelto, da de alta un partido de verdad en Captación → Partidos. Pide local, visitante, competición y si se ve en el campo o por vídeo, y quienes marques quedan como scouts del partido',
      'Eventos (reuniones, visitas, comidas…): nuevo campo opcional «Lugar», que se ve en el calendario',
      'Tareas de un jugador: al crearla (o al ligarla a un jugador desde el panel), sus encargados entran por defecto como «Adjuntos», para que les aparezca también a ellos. Se pueden quitar a mano',
      'La pestaña «Mi día» pasa a llamarse «Tareas». El calendario es su propia pestaña, «Calendario», justo al lado',
      'Calendario más fácil de leer: nueva vista «Agenda» (la de por defecto) con los siete días uno debajo de otro y cada cosa a todo el ancho — hora, título entero, jugador, categoría y quién lo lleva —, sin tener que ampliar nada. La vista «Columnas» sigue ahí y ahora muestra el título completo en varias líneas y el jugador. Al pulsar en el nombre de un día se abre ese día con la tarjeta de cada persona del equipo',
      'Los cumpleaños vuelven a la página de inicio (el resto de avisos sigue en la campana)',
      'El panel «Equipo» que había encima de Mi día (la tarea en curso de cada uno) se muda al calendario: al ampliar un día sale una tarjeta por persona con todo lo que tiene ese día — tareas, llamadas, partidos, eventos —, lo que está en curso resaltado y cuántas le quedan. Clic en una persona filtra el día a lo suyo. La nota libre («en Elche hasta el jueves») sigue ahí, en el día de hoy',
      'Calendario más simple: siete columnas, una por día, con todo lo de ese día en una lista — primero lo que tiene hora y debajo lo demás, sin franjas. Cada línea lleva las iniciales de a quién le toca',
      'Calendario: clic en la cabecera de un día (o en «+N más») lo amplía a pantalla completa, con el título entero, el jugador, la categoría y quién lo lleva. Desde ahí se salta a otro día o se vuelve a la semana',
      'Inicio más limpio: los avisos que ocupaban la parte de arriba (novedades de la app, contratos de representación en sus últimos 6 meses y partidos de hoy) ya no salen en la página. Están en la campana 🔔 de arriba a la derecha, que marca en rojo cuando hay algo nuevo',
      'Filtros: fuera las filas de botones. En Mi día (categoría), el calendario (tipo), la lista de todas las tareas (persona y origen) y Jugadores (estado y partner) ahora son desplegables',
      'Inicio: el aviso de contratos de representación se puede descartar con la ✕ y no vuelve a salir hasta que entre otro contrato en sus últimos 6 meses. El aviso de «acciones de Firmar para hoy» desaparece: esas acciones ya salen en el calendario y en Mi día como llamadas y reuniones',
      'Quitado el botón «Mi día» de arriba a la derecha (Mi día es ahora la primera pestaña de Mantenimiento) y el bloque «Mi día» de la página de Jugadores',
      'Eventos ⇄ Pipeline: un evento ligado a un jugador de Captación que está en el pipeline queda apuntado también en el historial de su tarjeta de Firmar (y se quita de ahí si borras el evento). Al revés ya pasaba: la próxima acción que pongas en la tarjeta sale en Mi día y en el calendario como llamada o reunión',
      'Nuevo evento: «Asisten» ocupa una sola fila de iniciales en vez de una etiqueta por persona',
      'Tablero de tareas: desaparece la vista de tarjetas en tres columnas. Ahora es siempre una lista compacta de una línea por tarea (también al agrupar por jugador o persona); siguen la tabla y la vista de semana',
      'Inicio: en Equipo y Postpartidos sale arriba un bloque «Mi día» con hasta 5 cosas de hoy (y lo vencido) y un enlace «Ver todo»',
      'Equipo: nuevo «Resumen de la semana» automático — tareas hechas, vencidas y creadas por persona, con la flecha de cambio respecto a la semana anterior. Se mueve con el mismo selector de semana',
      'Ficha de jugador → Tareas: la lista usa la misma fila de una línea que Mi día (estado, reprogramar y reasignar desde la propia fila), en vez de tarjetas en dos columnas',
      'Mi día: alta rápida en una línea encima de la lista. Escribe la tarea y pulsa Enter; «@» asigna a una persona (@nb, @nacho), «#» pone la categoría (#informe, #negociación), la fecha se entiende en texto (hoy, mañana, pasado mañana, viernes, 15/10) y «!» la marca como prioridad alta. Debajo se ve cómo se va a crear antes de pulsar Enter',
      'Mi día: en «Vencidas», botón «Seleccionar» para marcar varias y moverlas de golpe a hoy, a mañana o a la próxima semana',
      'Tareas que se repiten: en la tarea (y al crearla, en «Más opciones») se puede elegir «Repetir: cada semana / cada mes». Al completarla se crea sola la siguiente, con la fecha que toque',
      'Prioridad más simple: normal o alta. Las de prioridad alta llevan un punto rojo delante del título. En el panel de la tarea ya se pueden cambiar la prioridad y la fecha límite',
      'Las tareas completadas hace más de 30 días se archivan solas: dejan de salir en las listas (siguen contando en las estadísticas)',
      'Móvil: la barra de acciones en masa (seleccionar jugadores, mover vencidas) ya no queda tapada por la barra inferior',
      'Mantenimiento: nueva pestaña «Calendario» (entre Mi día y Jugadores). Una semana de toda la empresa de un vistazo: una fila por persona y una columna por día, con un chip por cada tarea, llamada o reunión de Firmar, postpartido, partido de Captación y evento, con su icono y su hora. Los partidos con varios scouts salen en la fila de cada uno',
      'Calendario: semana anterior / siguiente / Hoy, filtros por tipo y por persona, «Ocultar completadas», y dos modos — «Por persona» y «Por tipo» (partidos, llamadas y reuniones, postpartidos, tareas, eventos). Tu fila va arriba y resaltada; al final de cada fila, la carga de la semana (abiertas / total); y si alguien tiene dos partidos el mismo día, aviso de solape',
      'Calendario: clic en un chip lo abre; clic en un hueco da de alta una tarea o un evento con la persona y el día ya puestos. En el móvil se ve un día por pantalla (se pasa deslizando) con las personas plegables',
      'Eventos: «Evento» ya no obliga a elegir un jugador. Se puede apuntar cualquier cita, reunión, videollamada, sesión de análisis, comida, viaje o partido — general, ligado a jugadores de Mantenimiento o a un jugador de Captación —, con hora opcional, quién asiste y con fecha pasada para registrar lo que ya ocurrió. Se crean desde Mi día y desde el calendario, y se pueden editar y borrar',
      'Inicio: aviso con los partidos de hoy de todo el equipo (hora, partido y scouts), que sale de la misma lista que el calendario',
      'Mantenimiento: la pestaña «Tareas» pasa a ser «Mi día». En vez del tablero de tarjetas, una lista de una línea por cosa pendiente que junta todo lo tuyo: tareas, llamadas y reuniones del pipeline Firmar, postpartidos, partidos de Captación que tienes asignados (hoy y los próximos 7 días) y eventos',
      'Mi día: secciones plegables con contador — Vencidas (con botón «Mover todo a hoy»), Hoy (primero lo que tiene hora), Próximos 7 días agrupado por día, Sin fecha, Más adelante y Hechas hoy',
      'Mi día: cada fila lleva el icono del tipo, un círculo de estado que al pulsarlo pasa de pendiente a en curso y a hecha, el jugador (clic → su ficha), la categoría, la fecha y el responsable. Al pasar el ratón salen las acciones: hecha, reprogramar (hoy / mañana / próxima semana / elegir fecha), reasignar y abrir. En el móvil: deslizar a la derecha = hecha, a la izquierda = reprogramar',
      'Mi día: chips de categoría y un buscador de texto encima de la lista. El jugador ya no es una forma de agrupar por defecto: va como chip en cada fila',
      'Mi día: reprogramar o reasignar una acción de Firmar desde la lista la cambia también en su tarjeta del pipeline; completar un postpartido sigue pidiendo el link del vídeo; un partido se marca como visto',
      'El tablero de siempre (kanban, compacto, tabla, semana, agrupar por jugador o persona) sigue ahí: botón «Tablero» arriba a la derecha. Jugadores, Equipo y Postpartidos no cambian',
    ],
    adminItems: [
      'Tareas de Captación: el vínculo con la ficha de scouting necesita la columna tasks.scouting_player_id (migration_tasks_scouting_player.sql). Hasta ejecutarla, la tarea se guarda sin vínculo, con el nombre del jugador en la descripción',
      'Viajes: necesitan dos columnas nuevas en agenda_eventos, fecha_fin y zona (migration_agenda_viajes.sql). Hasta ejecutarlo, un viaje se guarda como evento de un solo día y sin zona. La ciudad de cada club sale de una tabla interna (lib/viajes.ts) con las ciudades principales; lo que no esté ahí cae en «la zona»',
      'Calendario (solo admins): salen los fines de contrato, de representación y con el club, el día que vencen',
      'Seguridad: dos SQL nuevos por ejecutar — seguridad_agenda_eventos.sql (candados de cuenta activa y solo-Captación en la tabla de eventos) y seguridad_tareas_solo_admin.sql (las tareas «solo admin» pasan a estar protegidas en la base, no solo ocultas en pantalla)',
      'App.tsx: las fichas a página completa (jugador, miembro) ya no sustituyen a la sección; la sección queda montada y escondida debajo (components/BajoCapa). Captación tiene un modo «solo» que pinta únicamente la ficha de un partido o de un jugador; lo usa App para las fichas flotantes',
      'Lugar de los eventos: necesita la columna agenda_eventos.lugar (migration_agenda_eventos_lugar.sql). Hasta ejecutarla, el lugar se ignora al guardar',
      'Tareas que se repiten: necesitan la columna tasks.recurrence (migration_tasks_recurrence.sql). Hasta ejecutarla, «Repetir» se ignora al guardar. La prioridad no necesita migración: tasks.priority ya existía',
      'Eventos sin jugador: necesitan la tabla nueva agenda_eventos (migration_agenda_eventos.sql). Hasta ejecutarla, solo se guardan los eventos con jugador de Mantenimiento, como antes',
      'Mi día: los admin tienen arriba a la derecha un selector de persona para ver «El día de X» en la misma pantalla',
      'lib/agendaItems.ts: lista unificada (tareas + Firmar + postpartidos + partidos + eventos) con tests; components/agenda/AgendaRow.tsx: la fila, pensada para reutilizarse en calendario, home y ficha de jugador',
    ],
  },
  {
    date: '2026-09-08',
    items: [
      'Ficha de partido: nuevo botón «Vista ampliada» (icono ⤢ junto al lápiz) que abre el partido a pantalla completa con los dos equipos en columnas, el texto completo de cada informe, resumen por scout y filtros por veredicto o scout',
      'Vista ampliada de partido: ya se puede añadir el propio informe a un jugador que ya tiene informe de otro scout, y editar o borrar los informes existentes desde ahí',
      'Carga inicial más rápida: las tablas grandes (informes, partidos, alineaciones, jugadores de captación…) se leen en paralelo en vez de página a página, así que «Sincronizando datos…» dura mucho menos',
      'Conclusiones · Llamar: nuevo botón «Ver por zonas» que abre a pantalla completa todos los jugadores en «Llamar» agrupados por zona geográfica, ordenados por prioridad (más informes «Llamar» primero, en empate el más reciente), para repartir las llamadas de un vistazo',
      'Login: el campo de email tiene el foco al abrir, y el mensaje de error ya distingue credenciales incorrectas de un fallo de conexión (antes ambos decían «Email o contraseña incorrectos»)',
      'Mensajes técnicos de "falta ejecutar el SQL/la migración" (Partidos, Firmar, asignar scout a un partido, Historial) ya no se muestran a todo el mundo: los scouts ven un mensaje normal, el aviso técnico solo lo ve un admin',
      'Diez retoques pequeños: emojis sueltos en botones (CSV, Imprimir/PDF, cola pendiente, Solo Captación, Confederación, Planificación, Mi día) cambiados por iconos, corregido "Año nasc." → "Año nac.", "Nac." ambiguo → "Nacionalidad", y el botón "silenciar" de avisos en Firmar con más contraste',
      'Campogramas (Conclusiones → Llamar/Seguir/Decidir, y Fin de contrato) con botón «Descargar imagen» para bajarlos como PNG y compartirlos fuera de la app',
      'Quitada la pestaña «Pretemporada» de Captación (ya no hacía falta)',
      'Ficha del jugador de Captación: además de los informes de partido ya se pueden meter otros tres tipos — «Personalidad y entorno» (quién lo cuenta y semáforo verde/ámbar/rojo), «Contractual» (cuánto contrato le queda, qué cobra, cláusula y si el dato es fiable) y «Opinión del mercado» (qué club, quién lo dice y nivel de interés). Se añaden desde el botón ▾ que hay junto a «Añadir informe», y si el jugador no tiene ninguno no ocupan nada en pantalla',
      'Informe contractual: si pones un fin de contrato distinto al de la ficha, te ofrece actualizarlo también allí, para no dejar dos fechas que se contradicen',
      'Los tres tipos nuevos salen también en el PDF de «Exportar informe», en su propio apartado, y el resumen de IA los tiene en cuenta',
      'Ficha del partido: la app avisa cuando el equipo que un jugador tiene en su ficha no es ninguno de los dos que juegan, y ofrece corregirlo de un clic. Si es del mismo club pero otra categoría (un Juv B en un partido del filial) propone directamente el equipo correcto; si es de un club que no juega ese partido, o no tiene equipo puesto, ofrece los dos. Sale al vincular un jugador nuevo y también, con el botón «Revisar», para repasar de golpe los que ya estaban vinculados con el equipo desactualizado',
      'Pipeline sale de Captación y pasa a ser una sección propia, «Pipeline», en la barra de arriba (y en la barra inferior del móvil). Dentro está el tablero Firmar de siempre, sin tocar nada, y una vista nueva',
      'Pipeline → nueva pestaña «Por zona»: la vista por zonas ya existía, pero estaba escondida en un selector pequeño dentro del tablero. Ahora es una pestaña propia, y el selector interno se queda con Estatus y Encargado. Además cambia de forma: las zonas pasan a una lista lateral (una tira arriba en móvil) con su recuento, el reparto por estatus y en rojo cuántas llevan demasiado sin tocarse — antes era una rejilla de tarjetas que empujaba el tablero fuera de la pantalla',
      'Pipeline → nueva pestaña «Avisos»: los avisos cruzados con el resto de la app (le vieron en un partido, cambió de club, informe nuevo, contrato acabando, sin encargado…) dejan de estar en un desplegable encima del tablero, donde había que abrirlo y luego abrir cada grupo. Ahora todos los grupos se ven a la vez en dos columnas, con lo urgente delante, un botón para quedarte solo con lo que requiere acción, y el número de avisos en la propia pestaña',
      'Pipeline → nueva pestaña «Por encargado»: el panel de trabajo de cada uno. Los firmados no salen (ni en los bloques, ni en el embudo, ni en la tabla: ya no son trabajo, solo se cuentan arriba), y cada tarjeta aparece en un único bloque —el más urgente que le toque— para que los números signifiquen algo. Cuatro bloques con lo que urge — qué toca hoy (acciones vencidas o de hoy), se están enfriando (las que pasan la cadencia de su estatus), mis calientes y las que esperan teléfono — y debajo el pipeline entero: un embudo por estatus que al pulsarlo filtra, y una tabla con estatus, zona, días parada y próxima acción, ordenable y descargable a CSV. Se abre en el tuyo y hay un desplegable para ver el de cualquier compañero',
      'Navegación: el botón «atrás» del navegador hace lo que uno espera. Abrir una ficha de scouting, un partido, una tarjeta de Firmar o una tarea y pulsar atrás cierra eso y te deja donde estabas — antes te sacaba de la sección entera. Las pestañas de segundo nivel (Captación → Partidos, Pipeline → Avisos, Distribución → Clubes, Mantenimiento → Equipo…) van ahora en la dirección, así que atrás también se mueve entre pestañas, y al volver a una sección la encuentras en la pestaña que dejaste',
      'Navegación: los enlaces llegan a donde dicen. Las «acciones de Firmar» del Dashboard, de Mi día y del buscador ⌘K abren la tarjeta en Pipeline (antes mandaban a Captación y la tarjeta no se abría); un resultado de tarea en ⌘K abre la tarea; «ir a Firmar» desde una ficha de scouting ya no deja Captación con el cuerpo vacío al volver; los enlaces de cabecera cierran la ficha o el club que tuvieras abierto (pulsar «Captación» con un club abierto seguía enseñando Distribución); Admin se abre desde cualquier sitio, también desde la ficha de un jugador, y al cerrarlo vuelves a donde estabas en vez de a Mantenimiento; y Distribución tiene por fin su enlace a Pipeline',
      'Navegación: los enlaces compartidos vuelven a funcionar. Pegar #/jugador/… o #/pipeline/avisos en una pestaña nueva abría siempre Mantenimiento porque la app pisaba la dirección con lo último guardado antes de leerla. Y #/pipeline no estaba registrado: ni compartirlo ni volver atrás hacia él hacía nada',
      'Mantenimiento → Jugadores: la vista de lista pasa a ser la de entrada, en vez de las tarjetas — con la cartera entera caben muchos más jugadores sin bajar. Las tarjetas y la tabla siguen ahí, y la app recuerda la que uses',
      'Mantenimiento → Jugadores: cada jugador tiene ahora un estado — Activo (lo gestionamos nosotros), Inactivo (nos ha dejado o el contrato de representación ha vencido) y Gestión partner (el día a día lo lleva el partner). Se pone desde «Editar ficha», y arriba del todo hay un filtro con el número de cada uno. **La lista arranca enseñando solo los Activos**; los otros se ven pulsando su botón o «Todos», donde los no activos llevan su chapa de color. Solo afecta a esta lista: un inactivo sigue saliendo en tareas, cumpleaños y buscador. Requiere ejecutar migration_player_estado.sql; mientras tanto todos se leen como activos y las fichas se siguen guardando igual',
      'Mantenimiento → Jugadores: nuevo filtro de Partner, en botones grandes arriba del todo (Todos · Toldra · Boulema · Sin partner) con el número de jugadores de cada uno. La lista de partners sale de los propios datos, así que si mañana entra un tercero aparece solo; y «Toldra», «Toldrá» y «toldra» cuentan como el mismo, enseñando la grafía más usada. Se combina con el buscador y con el resto de filtros, el desplegable de encargados pasa a contar solo dentro del partner elegido, y la elección se recuerda al cambiar de pantalla',
      'Tareas: nuevo selector «Todas · Mantenimiento · Captación» encima del tablero, con el número de cada uno. Captación son las próximas acciones que nacen de una tarjeta del pipeline de Firmar (llamar, conseguir teléfono, reunión…); Mantenimiento, todo lo demás. Se reconocen por el vínculo real con la tarjeta, así que siguen bien clasificadas aunque cambies el título o el tipo de la tarea. El filtro afecta también a los contadores de arriba (vencidas, hoy, esta semana, en progreso) y se recuerda al cambiar de pantalla',
      'Pipeline → Firmar: al abrir una tarjeta, debajo del jugador de Captación vinculado salen ya sus tres últimos informes — fecha, scout, veredicto, título y las dos primeras líneas. Al pulsar uno se despliega el texto entero ahí mismo, y si tiene más hay un «Ver los N» que abre la ficha. Antes había que salir a Captación, abrir la ficha y volver solo para leer un informe',
      'Pipeline → Avisos: cada aviso se puede resolver sin salir de la lista. «Posponer 7 días» (reloj) lo esconde y lo devuelve solo cuando pasa la semana; «Visto» (check) lo esconde mientras diga exactamente lo mismo, y lo devuelve si cambia — si el contrato pasa a otra fecha o el jugador cambia de club, vuelve a avisar. El contador de la pestaña baja al momento, y abajo hay un enlace para volver a ver los que has escondido. Es tuyo y de este navegador: no afecta a nadie más',
      'Pipeline → Firmar: cada tarjeta lleva ahora los días que lleva sin tocarse («12d») en vez de solo un punto de color — en rojo si ha pasado la cadencia de su estatus (caliente 10 días, templado 50, frío 90), en ámbar si está cerca, en gris si va bien. Antes el punto avisaba de que algo iba mal pero había que abrir la ficha para saber cuánto',
      'Pipeline → nueva vista «Timeline»: todo lo que se mueve en el pipeline de más reciente a más antiguo — apuntes (notas, llamadas, whatsapps, reuniones, entorno), cambios de estatus, jugadores que entran, firmas y las tareas que nacen de una próxima acción. Agrupado por día, con filtros por tipo, por persona y buscador. Al pulsar un movimiento se abre su tarjeta en Firmar',
      'Admin → nueva pestaña «Control de equipos»: cuadro de cobertura. Arriba, equipos, relevantes, % cubiertos, jugadores en Llamar y en Seguir. Debajo, el desglose por zona o por categoría (cobertura, jugadores, en Llamar y el reparto de etiquetas) ordenado por dónde hay más gente en Llamar, descargable a CSV. Y dos listas: los equipos con más jugadores en Llamar, y los relevantes que se están quedando sin cubrir. Con su propio selector de temporada o histórico',
      'Ficha del equipo: cuando la ★ o la ✓ vienen de una regla y no las has puesto tú, ahora se explica por qué («sale como relevante: 2 jugadores en Llamar») y los jugadores que cuentan llevan un punto ámbar. Antes podías ver un equipo marcado como relevante con todos sus jugadores sin etiqueta y no había forma de entenderlo: contaban por tener informes con veredicto Llamar',
      'Captación → Equipos: dos reglas automáticas. Un equipo con 2 o más jugadores «en Llamar» se marca solo como ★ relevante, y uno visto en 2 o más partidos como ✓ cubierto. Las marcas deducidas salen en un tono más claro para distinguirlas de las que pones tú, y arriba aparece «N equipos cumplen alguna regla — Aplicar» para guardarlas de golpe cuando quieras (hasta entonces solo se ven, no se toca nada)',
      'Un jugador cuenta como «en Llamar» si tiene esa etiqueta o si tiene algún informe con veredicto Llamar, y cuenta una sola vez aunque cumpla las dos cosas',
      'El recuento de arriba («X de Y relevantes cubiertos») y la columna ✓ de la tabla ya usan el mismo criterio: antes el resumen daba por cubierto cualquier equipo con un solo partido y la columna solo miraba la marca manual, así que los dos números no cuadraban',
      'Otra tanda de retoques de interfaz: los emojis que quedaban como icono en Conclusiones (candidatos, mapa, movimientos, aviso de «Decidir» parado, filtro de zona), Equipos (Zonas, Actualizar plantilla) y la lista de clubes (notas, negociaciones estancadas) pasan a iconos; las flechas ← → de cambiar semana en Tareas y Partidos también, y ahora dicen «semana anterior / siguiente» para quien navega con lector de pantalla',
      'En el mapa de Conclusiones, «× Posición» y «× Categoría» pasan a «Por posición» y «Por categoría»: ese × era un signo de multiplicar, pero parecía un botón de cerrar',
      'Accesibilidad y contraste: 14 botones que solo tenían un icono (volver, cerrar sesión, buscar, editar, eliminar, cancelar…) ya dicen qué hacen, y 24 iconos de acción que estaban en gris muy claro se ven ahora con contraste suficiente',
      'Vista ampliada de la ficha del jugador (botón ⤢): más ancha y con una barra de resumen arriba — informes de partido, cuántos son «Llamar», partidos vistos, fecha del último informe y, solo si los hay, cuántos informes de personalidad, contractuales o de mercado',
      'Arreglado: al pulsar un informe en Captación → Informes recientes, la ficha del jugador se abría y se cerraba ella sola al momento. Pasaba también, aunque se notaba menos, al abrir una ficha desde cualquier sitio que cambia de pestaña a la vez',
    ],
    adminItems: [
      'En la consola del navegador aparece «[carga] fase 2 … ms» con el tiempo de cada tabla, ordenado de mayor a menor, para localizar la lenta',
    ],
  },
  {
    date: '2026-09-05',
    items: [
      'Home de Mantenimiento: quitado el aviso «X partidos para ver hoy» — solo miraba el campo antiguo de un scout por partido y por eso se le veían solo los de Ibai, aunque hubiera más gente asignada',
      'Captación → Planificación: nuevo botón «Solo mis partidos» junto al selector de semana, para ver solo los partidos donde apareces en «Persona» (también se respeta al imprimir o exportar a Excel)',
    ],
  },
  {
    date: '2026-09-03',
    items: [
      'Planificación: la celda «Jugador» ya se puede tocar. «Jugador» = los nuestros que asignéis a mano a ese partido (clic en la celda para añadir o quitar, con ✕); si no hay ninguno, «Captación». Van en negrita también al imprimir y en Excel',
      'Planificación: clic en el partido para corregir local/visitante sin abrir la ficha completa (con enlace directo a la ficha si hace falta tocar algo más). En «Persona» ya se puede quitar cualquier nombre con la ✕, sea o no un perfil del sistema, y añadir cualquier nombre suelto (no solo los perfiles)',
      'Ficha del jugador (Mantenimiento y Captación): botón «Exportar informe» (icono ⬇, junto a Editar) que genera un PDF de una página con la ficha deportiva y todos los informes — listo para compartir. En Mantenimiento incluye contrato, informes de partido y notas de rendimiento; en Captación, la ficha y las observaciones. Ninguno de los dos lleva assessment, quién escribió cada informe ni datos personales (teléfono, familia…)',
      'Informe de Captación: ahora incluye arriba un resumen escrito por IA que sintetiza todas las observaciones sueltas de ese jugador en un párrafo (requiere desplegar la Edge Function «resumen-scouting» y configurar la clave de Anthropic — ver el propio archivo). Si falla o no está configurada, el informe se genera igual, solo que sin esa sección',
      'Distribución: al cerrar una negociación con un club, se anota solo un evento «Transferencia» en la Actividad del jugador (Mantenimiento) y sale un aviso para repasar a mano su club y contrato — no los cambia automáticamente',
      'Distribución: nueva temporada 2026-27, seleccionable en un desplegable junto al título (2025-26 queda como «archivada»: se sigue consultando tal cual, pero ya no recibe altas). Los clubes de 2025-26 se han copiado a 2026-27 (mismo nombre, liga, país, contacto y encargado) sin arrastrar solicitudes ni el marcador de contactado; los jugadores empiezan de cero en la temporada nueva. La pestaña Distribución de la ficha del jugador también tiene ahora su propio selector de temporada, para no mezclar situaciones de 25/26 y 26/27 en la misma lista',
      'Menos espera al entrar: cada tabla de fondo (clubes, informes, partidos…) ya aparece en cuanto llega, en vez de esperar a que las 16 terminen juntas; el aviso «Sincronizando datos…» solo sale si de verdad tarda más de medio segundo',
      'Captación → nueva pestaña «Planificación»: la hoja de fin de semana (Día · Hora · Partido · Jugador · Persona · Vía) que se hacía en Excel, ahora nativa. Semana de planificación de martes a lunes (por defecto) o solo fin de semana, con ← →, y botón flotante 🗓️ en todas las pantallas, jugadores nuestros en negrita (o «Captación»), edición directa en la tabla (quién lo ve, vía campo/tv por scout, hora y notas), partidos vistos tachados, «＋ Añadir partido», Imprimir/PDF y descarga a Excel',
      'Tabla de jugadores (Admin): botón de papelera en cada fila para eliminar, con confirmación. Aquí salen TODOS los jugadores, también los «solo Distribución» que no aparecen en Mantenimiento (llevan una etiqueta que lo indica)',
      'Nueva vista «Mi día» (☀️ en la barra inferior y en el menú): tus partidos de hoy, acciones del pipeline Firmar vencidas, tareas del día y postpartidos, en una sola lista con botones grandes de «Visto» y «Hecho»',
      'Captación: al crear un jugador o un partido, la app avisa si ya existe uno parecido («¿Es alguno de estos?») con un botón para abrirlo en vez de duplicarlo',
      'Captación: los informes se guardan como borrador mientras escribes y, si no hay cobertura al pulsar Guardar, se quedan en una cola que se envía sola cuando vuelve la señal (chip «📡 pendientes de enviar» en la cabecera)',
      'Firmar: escribir en Notas y enviar un apunte en el mismo gesto ya no borra las notas; cada cambio parchea solo su campo. Las notas se guardan solas mientras escribes',
      'Firmar y alineaciones: se distingue «cambió de club» de «cambió de equipo dentro del club» (Juv B → Juv A); Pegar alineación y Actualizar plantilla proponen corregir la categoría',
      'Si dos personas editan a la vez un jugador, un club o una negociación, la segunda ve un aviso con los campos que difieren y elige recargar o sobrescribir, en vez de pisar sin saberlo',
      'Contactos pasa a la base de datos: las correcciones, altas, bajas y favoritos se comparten entre todo el equipo (hasta que el admin pulse «Importar ahora» sigue funcionando como antes en cada navegador)',
      'Ficha de jugador y de club: sección «Historial de cambios» (quién cambió qué y cuándo)',
      'Estadísticas → Modelo «Llamar»: entrena en segundo plano sin bloquear la pantalla y recuerda el resultado; botón «Reentrenar»',
      'Correo diario a las 8:00 con tus partidos, acciones vencidas y tareas del día (cuando el admin lo active)',
      'Captación → Partidos: el buscador también encuentra partidos por jugador vinculado',
      'Listas de equipos, gestores, posiciones y ligas ordenadas con acentos correctos (Álava antes que Zaragoza)',
    ],
    adminItems: [
      'Planificación · nuestros a mano: tabla scouting_match_our_players (migration_match_nuestros.sql, incluida como PARTE 6 en migraciones_tanda2_todo.sql), realtime y RLS con candados cuenta_activa/captacion_only_fuera; sin la migración la celda sigue mostrando solo los deducidos por club',
      'Planificación: lib/planificacion.ts (lógica pura + HTML de impresión, tests/planificacion.test.ts), views/captacion/PlanificacionTab.tsx, cableado en Captacion.tsx; MatchFormPanel admite fechaInicial; csv.ts/BotonCsv aceptan nombre sin sello de fecha',
      'Admin → Historial (auditoría por tabla/fila, trigger audit_row en 7 tablas) y Admin → Errores (client_errors: ErrorBoundary + window.onerror + unhandledrejection, con throttle). SQL: migration_audit_log.sql, migration_client_errors.sql',
      'Contactos: migration_contactos_supabase.sql (tablas contactos + contactos_favoritos, RLS con cuenta_activa/captacion_only_fuera/freno_borrado, realtime). Importación desde Contactos → «Importar ahora» (solo admin, desde el navegador con los datos buenos)',
      'Conflictos: migration_updated_at_triggers.sql (updated_at + trigger set_updated_at en players, clubs, club_negotiations, captacion_firmas, scouting_players). db.ts actualizarConControl lanza ConflictError; App guardarConControl abre ConflictModal. Hasta ejecutar el SQL, players/clubs guardan sin control (42703) y avisan en consola',
      'Crear usuario desde Admin ahora usa la Edge Function crear-usuario (auth.admin.createUser con service role): antes signUp con la sesión del admin podía dejarle logueado como el usuario nuevo. Desplegar: supabase functions deploy crear-usuario',
      'Correo diario: Edge Function resumen-diario + migration_cron_resumen_diario.sql (pg_cron + pg_net + app_config). Secretos CRON_SECRET y APP_URL. Ver README',
      'Lecturas paginadas: dedupe por id en leerTodo y en los 13 bucles a mano (la paginación por offset repetía/saltaba filas si alguien insertaba entre páginas); refetchTable descarta respuestas fuera de orden (seqRef)',
      'Refactor: Captacion.tsx (9.300 líneas) → src/views/captacion/* (26 ficheros, máx 1.700); Distribution.tsx (5.400) → src/views/distribution/* + lib/distribution.ts (lógica pura con tests). Ningún cambio de comportamiento salvo el orden de los filtros del pipeline en escritorio',
      'ToastProvider único (contexts/ToastContext.tsx): PlayerDetail montaba 8 ToastStack. useToast() cae al contexto si existe',
      'lib/equipos.ts: equipoMatchKind/mismoEquipo/categoriaDe (club + categoría); lib/duplicados.ts; lib/colaInformes.ts; lib/miDia.ts; lib/modeloLlamar.ts (+ worker); lib/coleccion.ts; lib/formato.ts',
      'ESLint a CERO (eran 50). Nuevo .github/workflows/ci.yml: tsc + vitest + eslint --max-warnings=0 + build en cada push',
      '135 tests (eran 49)',
    ],
  },
  {
    date: '2026-09-02',
    items: [
      'Las tareas ya no salen «vencidas» el mismo día que vencen: en el tablero, en la ficha del jugador, en la de cada miembro y en el seguimiento de Admin. Antes, por un lío de zona horaria, una tarea que vencía hoy aparecía en rojo casi todo el día',
      'Lo que vence en domingo cuenta como «esta semana» (antes se quedaba fuera)',
      'La columna «Actividad 4 sem» ya no se desplaza un día tras el cambio de hora',
      'Captación: al abrir otro jugador, el formulario de nuevo informe empieza en blanco. Antes se quedaba el texto y el partido del jugador anterior y se podía guardar el informe en la ficha equivocada',
      'Captación: al editar el texto de un informe que venía de Boulema ya no se pierde su conclusión',
      'Captación: el «Limpiar filtros» de Partidos también quita «ocultar futuros»',
      'Estadísticas de scouts: los «debates pendientes» se calculan con la conclusión MÁS RECIENTE de cada scout, no con la más antigua',
      'Distribución: al mover una negociación de estado se actualiza al momento el reloj de «parada» (antes seguía en rojo hasta recargar)',
      'Distribución: la prioridad D ya se puede poner también al editar; el filtro de «demasiado joven» para las necesidades se calcula con el año actual en vez de estar fijo en 2009',
      'Ficha del jugador: si un guardado falla ahora sale un aviso y no se cierra el modo edición (antes parecía guardado y no lo estaba). Se valida el nombre y la fecha de nacimiento al editar, y los ficheros de contrato y pasaporte deben ser PDF/imagen de hasta 10 MB',
      'Panel de tarea: ya salen todos los tipos (Postpartido, Marketing, Comunicación) y al abrir otra tarea con ⌘K no se le pegaba el jugador de la anterior',
      'Búsqueda global: un usuario que no es admin ya no encuentra tareas «solo admin»',
      'Contactos: al vaciar un campo de un contacto se queda vacío tras recargar, y borrar y volver a crear un contacto propio ya no lo deja invisible',
      'Si falla la carga de tu perfil al entrar, sale un botón «Reintentar» en vez de una rueda infinita',
      'Boulema, Estadísticas de Captación y el panel de jugador de Captación van más ligeros',
    ],
    adminItems: [
      'Nuevo lib/fechas.ts (fechaLocal, hoyISO, parseDia, sumarDias, lunesDe, esVencida, diasHasta) con tests. Regla: los días se comparan como texto AAAA-MM-DD y si hace falta un Date se ancla a las 12:00 locales. Sustituye ~25 usos de new Date("AAAA-MM-DD") y toISOString().slice(0,10) repartidos por Dashboard, PlayerDetail, TeamMemberDetail, AdminPanel, TaskDetailPanel, Captación, Distribución e informeMensual',
      'TASK_LABELS en types.ts: única lista de tipos de tarea; los tres <select> la iteran',
      'Cuenta «solo Captación»: el guard se evalúa ANTES de las ramas de jugador/miembro/boulema y el router de hash ignora esas rutas. Antes #/jugador/<id> abría la ficha completa',
      'Tareas adminOnly filtradas en App (tasksVisibles) para PlayerDetail, TeamMemberDetail y GlobalSearch',
      'Handlers de realtime: leen refs (playersRef, tasksRef…) en vez de hacer setX(prev => { avisos; return prev }). Con StrictMode esos updaters se ejecutaban dos veces → campana y notificación del sistema duplicadas',
      'db.ts: updateNegotiation escribe updated_at y devuelve la fila; assignManagerToPlayers en lotes de 200 y comprueba errores; renombrarEquipo y mergeScoutingMatches comprueban errores; los 7 fetchers «opcionales» solo devuelven [] si la tabla no existe (42P01), cualquier otro fallo se propaga y sale el aviso rojo de carga incompleta',
      'CSV: se neutralizan celdas que empiezan por = + - @ (inyección de fórmulas en Excel)',
      'Edge functions: notify-task exige cabecera x-webhook-secret (⚠ hay que crear el secreto WEBHOOK_SECRET en la función y añadir la cabecera en el Database Webhook antes de desplegar, si no dejan de llegar los correos); leer-partido solo acepta URLs de sofascore/flashscore/besoccer/lapreferente/futbol-regional (era un proxy abierto)',
      'AuthContext: getSession con catch/finally y profileError + refreshProfile',
      'Eliminado código muerto: EditGeneralTaskModal (Dashboard), desplegables de encargado/contacto y selectedNeedPosition (Distribución). Componentes PanelExpandBtn, HealthCard, TaskCard, Group y Row sacados fuera del render (se remontaban en cada tecla)',
      'Índices Map en Boulema (peticiones), CaptacionStats, ScoutStats, ScoutingTable y las tres vistas de jugadores del Dashboard (openTasksByPlayer)',
      'Nuevo test de fechas y 2 tests de CSV: 49 tests en total',
    ],
  },
  {
    date: '2026-08-21',
    items: [
      'Distribución vuelve a ir rápida. La había ralentizado yo al poner los desplegables de encargado y contacto en cada fila de la lista de clubes: escribir en el buscador costaba una décima de segundo por tecla solo en recalcular los nombres de esos desplegables, y eso con 1.500 clubes en pantalla',
      'Las pestañas de Solicitudes, Encargados y el pipeline también van más ligeras',
    ],
    adminItems: [
      'nombreCorto() se llamaba dentro de cada <option> de cada fila (1.500 clubes × 2 desplegables × 10 perfiles = 30.000 llamadas por repintado) y cada una recorría la lista de perfiles entera para detectar nombres repetidos: ~300.000 troceos con regex. Medido en banco: 105 ms → 0,07 ms',
      'Las opciones de los desplegables se construyen una vez y se reutilizan en las 1.500 filas, en vez de crear 30.000 elementos',
      'Solicitudes: el contador de «ofrecidos» hacía un bucle anidado (400 solicitudes × 2.000 negociaciones × búsqueda del jugador) y encima duplicado, porque la lista se pinta para móvil y para escritorio. Ahora es un índice',
      'Clubes agrupados por liga: recorría los 1.500 clubes una vez por liga (~300) para partir la lista en trozos. Ahora se agrupa de una pasada',
      'Cambiados a índice los .find()/.filter() anidados de filteredEntries, distributionYears, byPriority, myPending, las tarjetas de Jugadores y la pestaña Encargados',
      'El contador del checkbox «Ocultar cerrados» costaba 600.000 comparaciones por repintado para enseñar un número entre paréntesis',
      'sessionStorage: se leía y parseaba el JSON de filtros en cada render; ahora solo al montar',
      'El buscador del pipeline hacía toLowerCase() una vez por negociación y por tecla',
    ],
  },
  {
    date: '2026-08-20',
    items: [
      'Las posiciones ya significan lo mismo en toda la app: «Segunda punta» salía como delantero en Captación y en el PDF, pero como «Otros» en las estadísticas de scouts. El mismo jugador contaba distinto según dónde lo mirases',
      'Boulema → Mantenimiento: la lista va más ligera (se pintaba dos veces, una para móvil y otra para escritorio, y se escondía una con CSS)',
      'Distribución → Oportunidades: el cruce de jugadores con las necesidades de los clubes va notablemente más rápido, sobre todo al escribir en los filtros',
    ],
    adminItems: [
      'Un solo clasificador de posición en lib/campo.ts. El grupo, la línea del PDF y la etiqueta de las estadísticas se DEDUCEN de él, así que ya no pueden volver a separarse',
      'Los 14 quita-acentos escritos a mano por toda la app pasan a ser uno solo en lib/texto.ts. Tres de ellos ya se habían separado del resto',
      'Descubierto de paso: esos 14 llevaban una «ñ» en la expresión regular que no servía de nada — NFD ya la había convertido en «n» dos pasos antes. Peña y Pena siempre han sido lo mismo al buscar (que es lo correcto, pero conviene saberlo)',
      'Los dos vocabularios de zona (el de los clubes y el que venía del Trello de firmas) estaban sueltos en el mismo archivo, uno encima del otro. Ahora están separados y explicados en lib/zonas.ts',
      'Oportunidades: buscaba cada jugador recorriendo la lista entera y volvía a normalizar el texto de cada petición dentro del bucle — decenas de miles de veces para sacar siempre lo mismo',
      'seasonEntries no estaba memoizado e invalidaba los tres cálculos más caros de Distribución en cada repintado',
      'Primeros tests: 41 sobre zonas, equipos, posiciones, texto, CSV y el pegado de alineaciones. Se ejecutan con «npm test»',
      'El primer test que escribí ya encontró un fallo: «C.F. Villarreal» dejaba colgando una «f» como si fuera parte del nombre del club, según se escribiera con puntos o sin ellos',
    ],
  },
  {
    date: '2026-08-20',
    items: [
      'Contactos abre mucho más rápido y, sobre todo, el resto de la app también: los 3.065 contactos iban metidos dentro del programa y se los descargaba todo el mundo aunque no entrase nunca ahí. Ahora se piden solo al abrir la pestaña',
      'La tabla de carga semanal por equipos estaba desplazada un día. Corregido',
      'Si al abrir la app falla la carga de algo (partidos, informes, clubes…), sale un aviso rojo diciendo QUÉ ha fallado, en vez de enseñar la lista vacía como si no hubiera datos',
      'Panel de tarea: si alguien cambiaba el estado de la tarea mientras tú escribías, te borraba el texto sin guardar. Ya no',
      'Avisos de «partido nuevo de su equipo»: dejan de saltar por confundir clubes distintos que empiezan igual (Real Madrid / Real Sociedad)',
    ],
    adminItems: [
      'Seguridad: las cuentas nuevas nacen PENDIENTES. Hasta que un admin las activa desde el panel, la base de datos no les entrega absolutamente nada. Antes, cualquiera que se registrase entraba con acceso completo a teléfonos, contratos y pasaportes',
      'Nuevo botón «Activar / ✓ Activa» en Admin → Equipo, y chip «Pendiente» en las cuentas sin aprobar. Sirve también para cortarle el acceso a alguien sin borrar su cuenta ni su historial',
      'Freno de borrado masivo: nadie que no sea admin puede borrar más de 25 filas de una tabla de una sola vez',
      'Pasaportes y contratos: los enlaces guardados duraban 10 AÑOS y abrían el documento sin login. Ahora se guarda la ruta y el enlace se firma al abrirlo, con 5 minutos de validez',
      'Paginación: varias consultas ordenaban por columnas repetidas (sort_pos, fecha, priority…), y en tablas de más de 1.000 filas eso hace que Postgres repita filas y se salte otras sin avisar. Todas llevan ya desempate por id',
      'Cuatro consultas más que seguían sin paginar (apuntes, reuniones y actividades) ya lo están',
      'La comparación de nombres de equipo vivía duplicada en dos sitios, con una versión antigua y con fallo en App.tsx. Ahora hay una sola en lib/equipos.ts',
      'Los enlaces a PDF que salen de las notas del contrato ya no se pintan directos: se validan y se firman al abrirlos',
    ],
  },
  {
    date: '2026-08-18',
    items: [
      'Nueva pestaña Captación → Equipos: el cuadro de control de qué equipos tenéis cubiertos por zona y categoría. Marcas con ★ los que te importan, y la app te dice de cada uno cuántos jugadores tienes apuntados, cuántos informes y cuántos partidos suyos habéis visto esta temporada',
      'Una tira roja arriba te señala dónde falta control («Madrid · Cadetes: 3 sin cubrir») y un clic te lleva a esos equipos',
      'Y puedes dar de alta equipos de los que todavía no tienes a nadie apuntado: son justo los que quieres detectar',
      'Al pulsar un equipo se abre a pantalla partida —la lista se estrecha, no se tapa— con su plantilla, sus partidos y sus marcas. El botón ⤢ lo abre entero',
      'Los botones «📍 Zonas» y «📋 Actualizar plantilla» se mudan de Jugadores a Equipos, que es su sitio',
      'Captación → Jugadores: tercera vista «⊞ Ampliada» con agencia, fin de contrato, zona, estatus en el pipeline y fecha del último informe, además de lo de siempre',
      'Y un botón «📍 Zonas» en esa misma barra para asignar o corregir la zona de cualquier club',
      'Filtro por zona geográfica en los campogramas: en Conclusiones y en Fin de contrato eliges zona (C. Valenciana, Cat/Ara/Bal, Madrid, Mur/Alm/CLM, Andalucía, Norte, CyL/Nav/Rioja, Canarias, Extremadura o Extranjero) y el campograma se queda solo con esos jugadores',
      'Captación → Partidos va mucho más rápido: la lista va ahora de 60 en 60 (como Jugadores) y el buscador ya no se atasca. La app estaba pintando los 1.900 partidos de golpe, dos veces, y recontando jugadores e informes de cada uno en cada tecla',
      'La agenda semanal y el aviso de partidos pendientes también se calculan una sola vez en lugar de en cada repintado',
      'Nueva conclusión «Visto» al escribir un informe: para cuando lo has visto y no da para concluir. No cuenta como veredicto — ni baja la exigencia del scout ni sale como desacuerdo con otro compañero',
      'Si dejas la app abierta y vuelves a ella (o se duerme el ordenador), se refresca sola: se acabó el «lo metí desde el móvil y en el ordenador no aparece hasta recargar»',
      'Ficha de partido: el ⇄ solo sale ya en informes sueltos. Los que pertenecen a otro partido se ven en gris con el nombre de ese partido, pero no se le pueden robar',
      'Y si un informe se enganchó al partido equivocado, se suelta desde el propio informe con «quitar del partido» — el informe no se borra, vuelve a la ficha del jugador',
      'Al escribir un informe desde la ficha del jugador, la app te propone el partido: un toque y queda vinculado (y si lo dejas suelto, te avisa de que no saldrá en la ficha del partido)',
      'Las tareas que vencen hoy dejan de aparecer como «vencidas» todo el día: era un lío de husos horarios',
      'Distribución y Captación van notablemente más rápidas al escribir en los buscadores y al abrir listas largas',
      'Los jugadores de Captación se sincronizan en vivo: si otro scout cambia una valoración o un contrato, lo ves sin recargar',
      'En el móvil ya puedes editar y borrar apuntes del pipeline (los botones solo salían al pasar el ratón)',
      '«Ocultar futuros» en Partidos ya no esconde los de hoy: oculta de mañana en adelante',
      'La ficha del partido se abre ahora a pantalla partida, con más información y sin ventana flotante',
      'Pegar alineación: copias el once de Sofascore, Flashscore o BeSoccer, lo pegas en la ficha del partido y la app te dice quién ya está en la BBDD (para vincularlo de golpe) y quién es nuevo (para crearlo con un clic)',
      'Y si alguno figura con otro equipo, te lo marca y lo corriges desde ahí mismo: la alineación del día manda sobre lo que hubiera en la ficha',
      'Botón «📋 Actualizar plantilla» en Captación → Jugadores: pegas la plantilla de un club y pone a todos esos jugadores en ese equipo de una vez — la forma rápida de ponerse al día con los fichajes sin ir partido a partido',
    ],
    adminItems: [
      'Revisión a fondo del código: tres consultas se cortaban en 1.000 filas sin avisar (jugadores, tareas y Boulema) — ya están paginadas',
      'Red de seguridad ante errores de pantalla: en vez de quedarse en blanco, sale un aviso con botón de recargar',
      'Contactos avisa de que sus cambios se guardan solo en ese dispositivo, mientras lo pasamos a la base de datos',
      'Seguridad: candado en la base de datos para que solo un admin cambie permisos, y las cuentas «solo Captación» dejan de recibir datos que no les tocan',
    ],
  },
  {
    date: '2026-08-17',
    items: [
      'Overview → Postpartidos: estadísticas de quién hace qué y qué jugadores acumulan más informes postpartido',
      'Añadir negociación en Distribución: el club se elige escribiendo en un buscador, se acabó el scroll infinito',
      'Botón «Ocultar futuros» en Captación → Partidos para quedarte solo con lo ya jugado',
      'La pestaña Informes muestra los últimos 150 de cada persona (antes 60)',
      'Pretemporada incluye ahora la Best Cup y cualquier partido de julio o agosto',
      'Fusión manual de partidos: botón «⇄ Fusionar» en Partidos — selecciona los duplicados, elige cuál se queda y su fecha, y el resto le pasa scouts, jugadores e informes',
      'Cuentas «solo Captación»: en Admin puedes restringir a cualquier miembro para que solo vea Jugadores, Partidos e Informes — ideal para colaboradores que meten informes',
      'Admin → Estadísticas → pestaña Scouts: análisis del trabajo de cada scout — volumen, muletillas, originalidad, conclusiones, congruencia con los demás, acierto y detección temprana — con glosario de cada métrica',
      'Y estadísticas del equipo completo: ritmo de 12 meses, embudo de la BBDD a la firma, consenso, debates pendientes (Llamar vs Descartar), destacados que se enfrían, reparto del esfuerzo y cobertura por posición',
      'Firmar: acción predefinida «📵 Conseguir teléfono» — al programar la próxima acción, un toque en 📵 la deja lista; la tarjeta del jugador muestra el 📵 y cada columna cuenta cuántos están sin número',
      'Nueva pestaña Captación → Fin de contrato: eliges el año (2026, 2027, 2028…) y ves quién acaba contrato, colocado por posición en lista o campograma, con su equipo y su agencia — y puedes corregir la fecha ahí mismo con el lápiz',
      'Ese campograma de mercado es tuyo: solo salen los jugadores marcados con ★, y en «Toda la BBDD» filtras por 1ª, 2ª y 1ª RFEF para ir añadiendo',
      'La pestaña Firmar pasa a llamarse Pipeline/Firmar y las pestañas de Captación se reordenan: Pipeline, Conclusiones, Fin de contrato, Jugadores, Informes…',
      'Avisos de tarjeta: si eres encargado de un jugador del pipeline, te llega notificación de cualquier cambio — estatus, próxima acción, apuntes, zona, notas — y también cuando te ponen como encargado',
      'En Fin de contrato cada jugador lleva su estatus del pipeline con color: Llamar, Caliente, Templado, Frío, Decidir o Firmado (y un punto hueco si aún no está en el pipeline)',
      'Ficha de partido: si un scout escribió su informe desde la ficha del jugador (sin enganchar el partido), ahora aparece igualmente en gris con un ⇄ para vincularlo al partido de un clic — se acabaron los informes que faltaban',
      'Estadísticas del equipo: las listas de debates pendientes y de destacados que se enfrían ya no se cortan — se despliegan enteras y se descargan a Excel; el embudo muestra además qué porcentaje pasa de cada etapa a la siguiente',
      'Admin → Estadísticas → Modelo de Llamar: aprende del texto de vuestros informes qué se dice de un jugador que acaba en «Llamar» y le pone probabilidad a cada informe — con la lista de «Seguir» que suenan a Llamar, los «Llamar» que el texto no sostiene, las palabras que más pesan y un probador donde pegar un informe nuevo',
    ],
  },
  {
    date: '2026-08-16',
    items: [
      'Ficha de partido: haz clic en cualquier partido de Captación y se abre una ventana con sus jugadores, informes y scouts',
      'Un partido puede tener varios scouts asignados, y cada uno marca su parte como vista por separado',
      'Varios informes del mismo jugador en el mismo partido: cada scout escribe el suyo (antes solo cabía uno)',
      'Los jugadores sugeridos al vincular ya no mezclan equipos parecidos (Real Madrid / Atlético Madrid / Atlético Baleares)',
      'La lista de sugeridos ya no se corta en 16: salen todos, y el buscador muestra hasta 60 resultados',
      'Tarjetas de club en Distribución: se acabó el texto montado sobre los avatares',
      'Los partidos duplicados (una copia por scout) se han fusionado en uno solo: 2001 → 1862 partidos',
      'Captación se sincroniza en vivo: si otro scout vincula un jugador o escribe un informe, lo ves sin recargar',
    ],
  },
  {
    date: '2026-08-07',
    items: [
      'Las próximas acciones de Firmar crean una tarea real en el tablero: asignada a su encargado y con la fecha como límite',
      'Sincronización en ambos sentidos: completa la tarea y se marca hecha en Firmar, o al revés',
      'Botón «Crear tareas» en la Agenda de Firmar para convertir de golpe las acciones que ya tenías',
    ],
  },
  {
    date: '2026-07-31',
    items: [
      'Nueva pestaña Captación → Firmar: el pipeline de captación activa (ex-Trello) con zonas, estatus, próximas acciones, avisos y agenda',
      'Boulema es ahora una sección propia, con pestaña de Mantenimiento para sus jugadores',
      'Búsqueda global: ⌘K en ordenador o el botón Buscar de la barra inferior en el móvil',
      'Barra de navegación inferior en el móvil y revamp móvil de Firmar',
      'Vista Semana en tareas y agenda semanal de partidos',
      'Estado del equipo automático: se muestra la tarea en curso de cada uno, sin actualizar nada a mano',
      'Enlaces compartibles: copia la URL de cualquier ficha y mándala por WhatsApp',
      'Avisos de contratos de representación que expiran, deshacer acciones, indicador de guardado y más',
      'Los jugadores ya cerrados desaparecen de clubes, pipeline y ofrecimientos (sus datos siguen en su ficha)',
      'La app avisa en la home cuando hay una versión nueva, con este panel de novedades',
      'Botón «Añadir a Firmar» en la ficha de cada jugador de Captación: crea su tarjeta en el pipeline ya vinculada',
    ],
  },
]
