// ── Versión de la app y novedades ────────────────────────────
// BUILD_ID lo inyecta vite en cada build (plugin build-id en vite.config.ts),
// que además emite /version.json con el mismo id. La app compara ambos
// periódicamente: si difieren, hay una versión nueva desplegada.
//
// CHANGELOG: añade una entrada arriba en cada deploy con cambios visibles.
// Tras actualizar, la home muestra "🆕 Novedades" con la última entrada
// hasta que el usuario la descarta.

export const BUILD_ID: string = typeof __BUILD_ID__ !== 'undefined' ? __BUILD_ID__ : 'dev'

export interface ChangelogEntry {
  date: string      // "YYYY-MM-DD"
  /** Novedades que ve todo el equipo en la pantalla de inicio */
  items: string[]
  /** Cambios técnicos o de administración: solo los ven los admin */
  adminItems?: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    date: '2026-09-03',
    items: [
      'Captación → nueva pestaña «Planificación»: la hoja de fin de semana (Día · Hora · Partido · Jugador · Persona · Vía) que se hacía en Excel, ahora nativa. Semana de planificación de martes a lunes (por defecto) o solo fin de semana, con ← →, y botón flotante 🗓️ en todas las pantallas, jugadores nuestros en negrita (o «Captación»), edición directa en la tabla (quién lo ve, vía campo/tv por scout, hora y notas), partidos vistos tachados, «＋ Añadir partido», Imprimir/PDF y descarga a Excel',
      'Tabla de jugadores (Admin): botón de papelera en cada fila para eliminar, con confirmación. Aquí salen TODOS los jugadores, también los «solo Distribución» que no aparecen en Mantenimiento (llevan una etiqueta que lo indica)',
      'Nueva vista «Mi día» (☀️ en la barra inferior y en el menú): tus partidos de hoy, acciones del pipeline Firmar vencidas, tareas del día y postpartidos, en una sola lista con botones grandes de «Visto» y «Hecho»',
      'Captación: al crear un jugador o un partido, la app avisa si ya existe uno parecido («¿Es alguno de estos?») con un botón para abrirlo en vez de duplicarlo',
      'Captación: los informes se guardan como borrador mientras escribes y, si no hay cobertura al pulsar Guardar, se quedan en una cola que se envía sola cuando vuelve la señal (chip «📡 pendientes de enviar» en la cabecera)',
      'Firmar: escribir en Notas y enviar un apunte en el mismo gesto ya no borra las notas; cada cambio parchea solo su campo. Las notas se guardan solas mientras escribes',
      'Firmar y alineaciones: se distingue «cambió de club» de «cambió de equipo dentro del club» (Juv B → Juv A); Pegar alineación y Actualizar plantilla proponen corregir la categoría',
      'Si dos personas editan a la vez un jugador, un club o una negociación, la segunda ve un aviso con los campos que difieren y elige recargar o sobrescribir, en vez de pisar sin saberlo',
      'Contactos pasa a la base de datos: las correcciones, altas, bajas y favoritos se comparten entre todo el equipo (hasta que el admin pulse «Importar ahora» sigue funcionando como antes en cada navegador)',
      'Ficha de jugador y de club: sección «Historial de cambios» (quién cambió qué y cuándo)',
      'Estadísticas → Modelo «Llamar»: entrena en segundo plano sin bloquear la pantalla y recuerda el resultado; botón «Reentrenar»',
      'Correo diario a las 8:00 con tus partidos, acciones vencidas y tareas del día (cuando el admin lo active)',
      'Captación → Partidos: el buscador también encuentra partidos por jugador vinculado',
      'Listas de equipos, gestores, posiciones y ligas ordenadas con acentos correctos (Álava antes que Zaragoza)',
    ],
    adminItems: [
      'Planificación: lib/planificacion.ts (lógica pura + HTML de impresión, tests/planificacion.test.ts), views/captacion/PlanificacionTab.tsx, cableado en Captacion.tsx; MatchFormPanel admite fechaInicial; csv.ts/BotonCsv aceptan nombre sin sello de fecha',
      'Admin → Historial (auditoría por tabla/fila, trigger audit_row en 7 tablas) y Admin → Errores (client_errors: ErrorBoundary + window.onerror + unhandledrejection, con throttle). SQL: migration_audit_log.sql, migration_client_errors.sql',
      'Contactos: migration_contactos_supabase.sql (tablas contactos + contactos_favoritos, RLS con cuenta_activa/captacion_only_fuera/freno_borrado, realtime). Importación desde Contactos → «Importar ahora» (solo admin, desde el navegador con los datos buenos)',
      'Conflictos: migration_updated_at_triggers.sql (updated_at + trigger set_updated_at en players, clubs, club_negotiations, captacion_firmas, scouting_players). db.ts actualizarConControl lanza ConflictError; App guardarConControl abre ConflictModal. Hasta ejecutar el SQL, players/clubs guardan sin control (42703) y avisan en consola',
      'Crear usuario desde Admin ahora usa la Edge Function crear-usuario (auth.admin.createUser con service role): antes signUp con la sesión del admin podía dejarle logueado como el usuario nuevo. Desplegar: supabase functions deploy crear-usuario',
      'Correo diario: Edge Function resumen-diario + migration_cron_resumen_diario.sql (pg_cron + pg_net + app_config). Secretos CRON_SECRET y APP_URL. Ver README',
      'Lecturas paginadas: dedupe por id en leerTodo y en los 13 bucles a mano (la paginación por offset repetía/saltaba filas si alguien insertaba entre páginas); refetchTable descarta respuestas fuera de orden (seqRef)',
      'Refactor: Captacion.tsx (9.300 líneas) → src/views/captacion/* (26 ficheros, máx 1.700); Distribution.tsx (5.400) → src/views/distribution/* + lib/distribution.ts (lógica pura con tests). Ningún cambio de comportamiento salvo el orden de los filtros del pipeline en escritorio',
      'ToastProvider único (contexts/ToastContext.tsx): PlayerDetail montaba 8 ToastStack. useToast() cae al contexto si existe',
      'lib/equipos.ts: equipoMatchKind/mismoEquipo/categoriaDe (club + categoría); lib/duplicados.ts; lib/colaInformes.ts; lib/miDia.ts; lib/modeloLlamar.ts (+ worker); lib/coleccion.ts; lib/formato.ts',
      'ESLint a CERO (eran 50). Nuevo .github/workflows/ci.yml: tsc + vitest + eslint --max-warnings=0 + build en cada push',
      '135 tests (eran 49)',
    ],
  },
  {
    date: '2026-09-02',
    items: [
      'Las tareas ya no salen «vencidas» el mismo día que vencen: en el tablero, en la ficha del jugador, en la de cada miembro y en el seguimiento de Admin. Antes, por un lío de zona horaria, una tarea que vencía hoy aparecía en rojo casi todo el día',
      'Lo que vence en domingo cuenta como «esta semana» (antes se quedaba fuera)',
      'La columna «Actividad 4 sem» ya no se desplaza un día tras el cambio de hora',
      'Captación: al abrir otro jugador, el formulario de nuevo informe empieza en blanco. Antes se quedaba el texto y el partido del jugador anterior y se podía guardar el informe en la ficha equivocada',
      'Captación: al editar el texto de un informe que venía de Boulema ya no se pierde su conclusión',
      'Captación: el «Limpiar filtros» de Partidos también quita «ocultar futuros»',
      'Estadísticas de scouts: los «debates pendientes» se calculan con la conclusión MÁS RECIENTE de cada scout, no con la más antigua',
      'Distribución: al mover una negociación de estado se actualiza al momento el reloj de «parada» (antes seguía en rojo hasta recargar)',
      'Distribución: la prioridad D ya se puede poner también al editar; el filtro de «demasiado joven» para las necesidades se calcula con el año actual en vez de estar fijo en 2009',
      'Ficha del jugador: si un guardado falla ahora sale un aviso y no se cierra el modo edición (antes parecía guardado y no lo estaba). Se valida el nombre y la fecha de nacimiento al editar, y los ficheros de contrato y pasaporte deben ser PDF/imagen de hasta 10 MB',
      'Panel de tarea: ya salen todos los tipos (Postpartido, Marketing, Comunicación) y al abrir otra tarea con ⌘K no se le pegaba el jugador de la anterior',
      'Búsqueda global: un usuario que no es admin ya no encuentra tareas «solo admin»',
      'Contactos: al vaciar un campo de un contacto se queda vacío tras recargar, y borrar y volver a crear un contacto propio ya no lo deja invisible',
      'Si falla la carga de tu perfil al entrar, sale un botón «Reintentar» en vez de una rueda infinita',
      'Boulema, Estadísticas de Captación y el panel de jugador de Captación van más ligeros',
    ],
    adminItems: [
      'Nuevo lib/fechas.ts (fechaLocal, hoyISO, parseDia, sumarDias, lunesDe, esVencida, diasHasta) con tests. Regla: los días se comparan como texto AAAA-MM-DD y si hace falta un Date se ancla a las 12:00 locales. Sustituye ~25 usos de new Date("AAAA-MM-DD") y toISOString().slice(0,10) repartidos por Dashboard, PlayerDetail, TeamMemberDetail, AdminPanel, TaskDetailPanel, Captación, Distribución e informeMensual',
      'TASK_LABELS en types.ts: única lista de tipos de tarea; los tres <select> la iteran',
      'Cuenta «solo Captación»: el guard se evalúa ANTES de las ramas de jugador/miembro/boulema y el router de hash ignora esas rutas. Antes #/jugador/<id> abría la ficha completa',
      'Tareas adminOnly filtradas en App (tasksVisibles) para PlayerDetail, TeamMemberDetail y GlobalSearch',
      'Handlers de realtime: leen refs (playersRef, tasksRef…) en vez de hacer setX(prev => { avisos; return prev }). Con StrictMode esos updaters se ejecutaban dos veces → campana y notificación del sistema duplicadas',
      'db.ts: updateNegotiation escribe updated_at y devuelve la fila; assignManagerToPlayers en lotes de 200 y comprueba errores; renombrarEquipo y mergeScoutingMatches comprueban errores; los 7 fetchers «opcionales» solo devuelven [] si la tabla no existe (42P01), cualquier otro fallo se propaga y sale el aviso rojo de carga incompleta',
      'CSV: se neutralizan celdas que empiezan por = + - @ (inyección de fórmulas en Excel)',
      'Edge functions: notify-task exige cabecera x-webhook-secret (⚠ hay que crear el secreto WEBHOOK_SECRET en la función y añadir la cabecera en el Database Webhook antes de desplegar, si no dejan de llegar los correos); leer-partido solo acepta URLs de sofascore/flashscore/besoccer/lapreferente/futbol-regional (era un proxy abierto)',
      'AuthContext: getSession con catch/finally y profileError + refreshProfile',
      'Eliminado código muerto: EditGeneralTaskModal (Dashboard), desplegables de encargado/contacto y selectedNeedPosition (Distribución). Componentes PanelExpandBtn, HealthCard, TaskCard, Group y Row sacados fuera del render (se remontaban en cada tecla)',
      'Índices Map en Boulema (peticiones), CaptacionStats, ScoutStats, ScoutingTable y las tres vistas de jugadores del Dashboard (openTasksByPlayer)',
      'Nuevo test de fechas y 2 tests de CSV: 49 tests en total',
    ],
  },
  {
    date: '2026-08-21',
    items: [
      'Distribución vuelve a ir rápida. La había ralentizado yo al poner los desplegables de encargado y contacto en cada fila de la lista de clubes: escribir en el buscador costaba una décima de segundo por tecla solo en recalcular los nombres de esos desplegables, y eso con 1.500 clubes en pantalla',
      'Las pestañas de Solicitudes, Encargados y el pipeline también van más ligeras',
    ],
    adminItems: [
      'nombreCorto() se llamaba dentro de cada <option> de cada fila (1.500 clubes × 2 desplegables × 10 perfiles = 30.000 llamadas por repintado) y cada una recorría la lista de perfiles entera para detectar nombres repetidos: ~300.000 troceos con regex. Medido en banco: 105 ms → 0,07 ms',
      'Las opciones de los desplegables se construyen una vez y se reutilizan en las 1.500 filas, en vez de crear 30.000 elementos',
      'Solicitudes: el contador de «ofrecidos» hacía un bucle anidado (400 solicitudes × 2.000 negociaciones × búsqueda del jugador) y encima duplicado, porque la lista se pinta para móvil y para escritorio. Ahora es un índice',
      'Clubes agrupados por liga: recorría los 1.500 clubes una vez por liga (~300) para partir la lista en trozos. Ahora se agrupa de una pasada',
      'Cambiados a índice los .find()/.filter() anidados de filteredEntries, distributionYears, byPriority, myPending, las tarjetas de Jugadores y la pestaña Encargados',
      'El contador del checkbox «Ocultar cerrados» costaba 600.000 comparaciones por repintado para enseñar un número entre paréntesis',
      'sessionStorage: se leía y parseaba el JSON de filtros en cada render; ahora solo al montar',
      'El buscador del pipeline hacía toLowerCase() una vez por negociación y por tecla',
    ],
  },
  {
    date: '2026-08-20',
    items: [
      'Las posiciones ya significan lo mismo en toda la app: «Segunda punta» salía como delantero en Captación y en el PDF, pero como «Otros» en las estadísticas de scouts. El mismo jugador contaba distinto según dónde lo mirases',
      'Boulema → Mantenimiento: la lista va más ligera (se pintaba dos veces, una para móvil y otra para escritorio, y se escondía una con CSS)',
      'Distribución → Oportunidades: el cruce de jugadores con las necesidades de los clubes va notablemente más rápido, sobre todo al escribir en los filtros',
    ],
    adminItems: [
      'Un solo clasificador de posición en lib/campo.ts. El grupo, la línea del PDF y la etiqueta de las estadísticas se DEDUCEN de él, así que ya no pueden volver a separarse',
      'Los 14 quita-acentos escritos a mano por toda la app pasan a ser uno solo en lib/texto.ts. Tres de ellos ya se habían separado del resto',
      'Descubierto de paso: esos 14 llevaban una «ñ» en la expresión regular que no servía de nada — NFD ya la había convertido en «n» dos pasos antes. Peña y Pena siempre han sido lo mismo al buscar (que es lo correcto, pero conviene saberlo)',
      'Los dos vocabularios de zona (el de los clubes y el que venía del Trello de firmas) estaban sueltos en el mismo archivo, uno encima del otro. Ahora están separados y explicados en lib/zonas.ts',
      'Oportunidades: buscaba cada jugador recorriendo la lista entera y volvía a normalizar el texto de cada petición dentro del bucle — decenas de miles de veces para sacar siempre lo mismo',
      'seasonEntries no estaba memoizado e invalidaba los tres cálculos más caros de Distribución en cada repintado',
      'Primeros tests: 41 sobre zonas, equipos, posiciones, texto, CSV y el pegado de alineaciones. Se ejecutan con «npm test»',
      'El primer test que escribí ya encontró un fallo: «C.F. Villarreal» dejaba colgando una «f» como si fuera parte del nombre del club, según se escribiera con puntos o sin ellos',
    ],
  },
  {
    date: '2026-08-20',
    items: [
      'Contactos abre mucho más rápido y, sobre todo, el resto de la app también: los 3.065 contactos iban metidos dentro del programa y se los descargaba todo el mundo aunque no entrase nunca ahí. Ahora se piden solo al abrir la pestaña',
      'La tabla de carga semanal por equipos estaba desplazada un día. Corregido',
      'Si al abrir la app falla la carga de algo (partidos, informes, clubes…), sale un aviso rojo diciendo QUÉ ha fallado, en vez de enseñar la lista vacía como si no hubiera datos',
      'Panel de tarea: si alguien cambiaba el estado de la tarea mientras tú escribías, te borraba el texto sin guardar. Ya no',
      'Avisos de «partido nuevo de su equipo»: dejan de saltar por confundir clubes distintos que empiezan igual (Real Madrid / Real Sociedad)',
    ],
    adminItems: [
      'Seguridad: las cuentas nuevas nacen PENDIENTES. Hasta que un admin las activa desde el panel, la base de datos no les entrega absolutamente nada. Antes, cualquiera que se registrase entraba con acceso completo a teléfonos, contratos y pasaportes',
      'Nuevo botón «Activar / ✓ Activa» en Admin → Equipo, y chip «Pendiente» en las cuentas sin aprobar. Sirve también para cortarle el acceso a alguien sin borrar su cuenta ni su historial',
      'Freno de borrado masivo: nadie que no sea admin puede borrar más de 25 filas de una tabla de una sola vez',
      'Pasaportes y contratos: los enlaces guardados duraban 10 AÑOS y abrían el documento sin login. Ahora se guarda la ruta y el enlace se firma al abrirlo, con 5 minutos de validez',
      'Paginación: varias consultas ordenaban por columnas repetidas (sort_pos, fecha, priority…), y en tablas de más de 1.000 filas eso hace que Postgres repita filas y se salte otras sin avisar. Todas llevan ya desempate por id',
      'Cuatro consultas más que seguían sin paginar (apuntes, reuniones y actividades) ya lo están',
      'La comparación de nombres de equipo vivía duplicada en dos sitios, con una versión antigua y con fallo en App.tsx. Ahora hay una sola en lib/equipos.ts',
      'Los enlaces a PDF que salen de las notas del contrato ya no se pintan directos: se validan y se firman al abrirlos',
    ],
  },
  {
    date: '2026-08-18',
    items: [
      'Nueva pestaña Captación → Equipos: el cuadro de control de qué equipos tenéis cubiertos por zona y categoría. Marcas con ★ los que te importan, y la app te dice de cada uno cuántos jugadores tienes apuntados, cuántos informes y cuántos partidos suyos habéis visto esta temporada',
      'Una tira roja arriba te señala dónde falta control («Madrid · Cadetes: 3 sin cubrir») y un clic te lleva a esos equipos',
      'Y puedes dar de alta equipos de los que todavía no tienes a nadie apuntado: son justo los que quieres detectar',
      'Al pulsar un equipo se abre a pantalla partida —la lista se estrecha, no se tapa— con su plantilla, sus partidos y sus marcas. El botón ⤢ lo abre entero',
      'Los botones «📍 Zonas» y «📋 Actualizar plantilla» se mudan de Jugadores a Equipos, que es su sitio',
      'Captación → Jugadores: tercera vista «⊞ Ampliada» con agencia, fin de contrato, zona, estatus en el pipeline y fecha del último informe, además de lo de siempre',
      'Y un botón «📍 Zonas» en esa misma barra para asignar o corregir la zona de cualquier club',
      'Filtro por zona geográfica en los campogramas: en Conclusiones y en Fin de contrato eliges zona (C. Valenciana, Cat/Ara/Bal, Madrid, Mur/Alm/CLM, Andalucía, Norte, CyL/Nav/Rioja, Canarias, Extremadura o Extranjero) y el campograma se queda solo con esos jugadores',
      'Captación → Partidos va mucho más rápido: la lista va ahora de 60 en 60 (como Jugadores) y el buscador ya no se atasca. La app estaba pintando los 1.900 partidos de golpe, dos veces, y recontando jugadores e informes de cada uno en cada tecla',
      'La agenda semanal y el aviso de partidos pendientes también se calculan una sola vez en lugar de en cada repintado',
      'Nueva conclusión «Visto» al escribir un informe: para cuando lo has visto y no da para concluir. No cuenta como veredicto — ni baja la exigencia del scout ni sale como desacuerdo con otro compañero',
      'Si dejas la app abierta y vuelves a ella (o se duerme el ordenador), se refresca sola: se acabó el «lo metí desde el móvil y en el ordenador no aparece hasta recargar»',
      'Ficha de partido: el ⇄ solo sale ya en informes sueltos. Los que pertenecen a otro partido se ven en gris con el nombre de ese partido, pero no se le pueden robar',
      'Y si un informe se enganchó al partido equivocado, se suelta desde el propio informe con «quitar del partido» — el informe no se borra, vuelve a la ficha del jugador',
      'Al escribir un informe desde la ficha del jugador, la app te propone el partido: un toque y queda vinculado (y si lo dejas suelto, te avisa de que no saldrá en la ficha del partido)',
      'Las tareas que vencen hoy dejan de aparecer como «vencidas» todo el día: era un lío de husos horarios',
      'Distribución y Captación van notablemente más rápidas al escribir en los buscadores y al abrir listas largas',
      'Los jugadores de Captación se sincronizan en vivo: si otro scout cambia una valoración o un contrato, lo ves sin recargar',
      'En el móvil ya puedes editar y borrar apuntes del pipeline (los botones solo salían al pasar el ratón)',
      '«Ocultar futuros» en Partidos ya no esconde los de hoy: oculta de mañana en adelante',
      'La ficha del partido se abre ahora a pantalla partida, con más información y sin ventana flotante',
      'Pegar alineación: copias el once de Sofascore, Flashscore o BeSoccer, lo pegas en la ficha del partido y la app te dice quién ya está en la BBDD (para vincularlo de golpe) y quién es nuevo (para crearlo con un clic)',
      'Y si alguno figura con otro equipo, te lo marca y lo corriges desde ahí mismo: la alineación del día manda sobre lo que hubiera en la ficha',
      'Botón «📋 Actualizar plantilla» en Captación → Jugadores: pegas la plantilla de un club y pone a todos esos jugadores en ese equipo de una vez — la forma rápida de ponerse al día con los fichajes sin ir partido a partido',
    ],
    adminItems: [
      'Revisión a fondo del código: tres consultas se cortaban en 1.000 filas sin avisar (jugadores, tareas y Boulema) — ya están paginadas',
      'Red de seguridad ante errores de pantalla: en vez de quedarse en blanco, sale un aviso con botón de recargar',
      'Contactos avisa de que sus cambios se guardan solo en ese dispositivo, mientras lo pasamos a la base de datos',
      'Seguridad: candado en la base de datos para que solo un admin cambie permisos, y las cuentas «solo Captación» dejan de recibir datos que no les tocan',
    ],
  },
  {
    date: '2026-08-17',
    items: [
      'Overview → Postpartidos: estadísticas de quién hace qué y qué jugadores acumulan más informes postpartido',
      'Añadir negociación en Distribución: el club se elige escribiendo en un buscador, se acabó el scroll infinito',
      'Botón «Ocultar futuros» en Captación → Partidos para quedarte solo con lo ya jugado',
      'La pestaña Informes muestra los últimos 150 de cada persona (antes 60)',
      'Pretemporada incluye ahora la Best Cup y cualquier partido de julio o agosto',
      'Fusión manual de partidos: botón «⇄ Fusionar» en Partidos — selecciona los duplicados, elige cuál se queda y su fecha, y el resto le pasa scouts, jugadores e informes',
      'Cuentas «solo Captación»: en Admin puedes restringir a cualquier miembro para que solo vea Jugadores, Partidos e Informes — ideal para colaboradores que meten informes',
      'Admin → Estadísticas → pestaña Scouts: análisis del trabajo de cada scout — volumen, muletillas, originalidad, conclusiones, congruencia con los demás, acierto y detección temprana — con glosario de cada métrica',
      'Y estadísticas del equipo completo: ritmo de 12 meses, embudo de la BBDD a la firma, consenso, debates pendientes (Llamar vs Descartar), destacados que se enfrían, reparto del esfuerzo y cobertura por posición',
      'Firmar: acción predefinida «📵 Conseguir teléfono» — al programar la próxima acción, un toque en 📵 la deja lista; la tarjeta del jugador muestra el 📵 y cada columna cuenta cuántos están sin número',
      'Nueva pestaña Captación → Fin de contrato: eliges el año (2026, 2027, 2028…) y ves quién acaba contrato, colocado por posición en lista o campograma, con su equipo y su agencia — y puedes corregir la fecha ahí mismo con el lápiz',
      'Ese campograma de mercado es tuyo: solo salen los jugadores marcados con ★, y en «Toda la BBDD» filtras por 1ª, 2ª y 1ª RFEF para ir añadiendo',
      'La pestaña Firmar pasa a llamarse Pipeline/Firmar y las pestañas de Captación se reordenan: Pipeline, Conclusiones, Fin de contrato, Jugadores, Informes…',
      'Avisos de tarjeta: si eres encargado de un jugador del pipeline, te llega notificación de cualquier cambio — estatus, próxima acción, apuntes, zona, notas — y también cuando te ponen como encargado',
      'En Fin de contrato cada jugador lleva su estatus del pipeline con color: Llamar, Caliente, Templado, Frío, Decidir o Firmado (y un punto hueco si aún no está en el pipeline)',
      'Ficha de partido: si un scout escribió su informe desde la ficha del jugador (sin enganchar el partido), ahora aparece igualmente en gris con un ⇄ para vincularlo al partido de un clic — se acabaron los informes que faltaban',
      'Estadísticas del equipo: las listas de debates pendientes y de destacados que se enfrían ya no se cortan — se despliegan enteras y se descargan a Excel; el embudo muestra además qué porcentaje pasa de cada etapa a la siguiente',
      'Admin → Estadísticas → Modelo de Llamar: aprende del texto de vuestros informes qué se dice de un jugador que acaba en «Llamar» y le pone probabilidad a cada informe — con la lista de «Seguir» que suenan a Llamar, los «Llamar» que el texto no sostiene, las palabras que más pesan y un probador donde pegar un informe nuevo',
    ],
  },
  {
    date: '2026-08-16',
    items: [
      'Ficha de partido: haz clic en cualquier partido de Captación y se abre una ventana con sus jugadores, informes y scouts',
      'Un partido puede tener varios scouts asignados, y cada uno marca su parte como vista por separado',
      'Varios informes del mismo jugador en el mismo partido: cada scout escribe el suyo (antes solo cabía uno)',
      'Los jugadores sugeridos al vincular ya no mezclan equipos parecidos (Real Madrid / Atlético Madrid / Atlético Baleares)',
      'La lista de sugeridos ya no se corta en 16: salen todos, y el buscador muestra hasta 60 resultados',
      'Tarjetas de club en Distribución: se acabó el texto montado sobre los avatares',
      'Los partidos duplicados (una copia por scout) se han fusionado en uno solo: 2001 → 1862 partidos',
      'Captación se sincroniza en vivo: si otro scout vincula un jugador o escribe un informe, lo ves sin recargar',
    ],
  },
  {
    date: '2026-08-07',
    items: [
      'Las próximas acciones de Firmar crean una tarea real en el tablero: asignada a su encargado y con la fecha como límite',
      'Sincronización en ambos sentidos: completa la tarea y se marca hecha en Firmar, o al revés',
      'Botón «Crear tareas» en la Agenda de Firmar para convertir de golpe las acciones que ya tenías',
    ],
  },
  {
    date: '2026-07-31',
    items: [
      'Nueva pestaña Captación → Firmar: el pipeline de captación activa (ex-Trello) con zonas, estatus, próximas acciones, avisos y agenda',
      'Boulema es ahora una sección propia, con pestaña de Mantenimiento para sus jugadores',
      'Búsqueda global: ⌘K en ordenador o el botón Buscar de la barra inferior en el móvil',
      'Barra de navegación inferior en el móvil y revamp móvil de Firmar',
      'Vista Semana en tareas y agenda semanal de partidos',
      'Estado del equipo automático: se muestra la tarea en curso de cada uno, sin actualizar nada a mano',
      'Enlaces compartibles: copia la URL de cualquier ficha y mándala por WhatsApp',
      'Avisos de contratos de representación que expiran, deshacer acciones, indicador de guardado y más',
      'Los jugadores ya cerrados desaparecen de clubes, pipeline y ofrecimientos (sus datos siguen en su ficha)',
      'La app avisa en la home cuando hay una versión nueva, con este panel de novedades',
      'Botón «Añadir a Firmar» en la ficha de cada jugador de Captación: crea su tarjeta en el pipeline ya vinculada',
    ],
  },
]
