-- 88 clubs from Distribucion AIS - Summer 2026
INSERT INTO clubs (name, league, country, contact_person, ais_manager, notes, is_priority) VALUES
  ('Deportivo', 'Spain 2', 'Spain', 'Fernando Soriano', 'PP/BGF', 'Ofrecidos: Budesca, De Roa , Carvalho, Pedro Fidel, Petit, Ferrari,', false),
  ('Racing Santander', 'Spain 2', 'Spain', 'Chema Aragon /  Jorge Ripolles', 'PP/BGF', 'Ofrecidos: De Roa, Carvalho, Budesca, Pedro Fidel, Ferrari, Pastor., Petit', false),
  ('Almeria', 'Spain 2', 'Spain', 'Joao / Iban', 'PP / BGF', NULL, false),
  ('Valladolid', 'Spain 2', 'Spain', 'Victor Orta / Alberto Cordero', 'PP / BGF', 'Ofrecidos: Pablo Felipe, De Roa, Rica, Pedro Fidel', false),
  ('Eibar', 'Spain 2', 'Spain', 'Cesar Palacios / Eneko Romo', 'PP / AV', 'Ofrecidos: De Roa, Miguel Carvalho | Lateral izquierdo, extremo derecho, box to box', false),
  ('Leganes', 'Spain 2', 'Spain', 'Andres Pardo / Diego Perez', 'PP / AV', 'Ofrecidos: De Roa, Miguel Carvalho, Pastor, Pedro Fidel | aún no definido posiciones', false),
  ('Las Palmas', 'Spain 2', 'Spain', 'Luis Helguera / Vicente Gomez', 'NB', 'Ofrecidos: De Roa, Miguel Carvalho, Pastor, Pedro Fidel | todas las posiciones', false),
  ('Tenerife', 'Spain 2', 'Spain', 'Hugo Rico', 'NB', 'Ofrecidos: De Roa, Miguel Carvalho, Pastor, Pedro Fidel | Lateral izquierdo, central, mediocentro', false),
  ('Castellon', 'Spain 2', 'Spain', 'Ramon Soria', 'LT / PP', 'Mediocentro, central, extremo, 9', false),
  ('Malaga', 'Spain 2', 'Spain', 'Loren Juarros / Fran Capote', 'LT / AV / PP', NULL, false),
  ('Zaragoza', 'Spain 2', 'Spain', 'Lalo Arantegui / Quique García', 'LT / AV', 'Ofrecidos: Carlos de Roa | el club está interesado', false),
  ('Cordoba', 'Spain 2', 'Spain', 'Juanito', 'LT', 'Entra cualquier jugador que mejore la actual plantilla, sobretodo buscan un perfil de 6/8.', false),
  ('Ceuta', 'Spain 2', 'Spain', 'Edu Villegas / Blanki', 'BGF / PP', NULL, false),
  ('Granada', 'Spain 2', 'Spain', 'Javier Alonso/', 'BGF / PP', NULL, false),
  ('Albacete', 'Spain 2', 'Spain', 'Toche', 'BGF / AV', 'Ofrecidos: De Roa, Gozalbez, Pedro Fidel, Carvalho | Buscan reforzar la plantilla, excepto LD, acaban de renovar dos jugadores.', false),
  ('Cadiz', 'Spain 2', 'Spain', 'Juan Cala', 'BGF / AV', 'No quieren oir hablar de nada, hasta que esten mas tranquilos.', false),
  ('Sporting', 'Spain 2', 'Spain', 'Israel Villaseñor', 'BGF', NULL, false),
  ('Huesca', 'Spain 3', 'Spain', 'Javier Sanz', 'AV', 'Ofrecidos: De Roa, Pedro Fidel, Vicente Esquerdo.', false),
  ('Andorra', 'Spain 2', 'Spain', 'Jaume Nogues', 'AV', 'Ofrecidos: De Roa, Pedro Fidel, Pablo Gozalbez. | 1º valoran al jugador y después deciden como quieren abordarlo si lo quieren, buscan en esa poscion, pero en principio querrian tener al jugador en propiedad, interesaria con porcentajes de futura venta.', false),
  ('Burgos', 'Spain 2', 'Spain', 'Michu', 'AV', 'Ofrecidos: De Roa, Rica, Carvalho | Sin tenerlo definido', false),
  ('Real Sociedad B', 'Spain 2', 'Spain', NULL, NULL, NULL, false),
  ('Alcorcon', 'Spain 3', 'Spain', 'Alberto Lozano', 'PP', 'Ofrecidos: Vicente Esquerdo | Quieren a Vicente y pasaran propuesta', false),
  ('Algeciras', 'Spain 3', 'Spain', 'Jordi Figueras', NULL, 'Pendiente conseguir contacto', false),
  ('Antequera', 'Spain 3', 'Spain', 'Alberto Aguilar', 'AV', 'Ofrecidos: Pedro Fidel, Carlos de Roa, Rica Funez, David Selles | Necesidades en todas las posiciones excepto en el centro del campo.', false),
  ('Arenas', 'Spain 3', 'Spain', NULL, 'PP', NULL, false),
  ('Atletico B', 'Spain 3', 'Spain', NULL, 'LT', NULL, false),
  ('Barakaldo', 'Spain 3', 'Spain', 'Joseba Nuñez', 'PP / NB', NULL, false),
  ('Betis B', 'Spain 3', 'Spain', 'Fajardo', 'PP / BGF', NULL, false),
  ('Cacereño', 'Spain 3', 'Spain', 'Francis Bordallo', NULL, 'Pendiente conseguir contacto', false),
  ('Cartagena', 'Spain 3', 'Spain', 'Javi Hernandez', 'AV', NULL, false),
  ('Cultural Leonesa', 'Spain 3', 'Spain', NULL, NULL, NULL, false),
  ('Deportivo B', 'Spain 3', 'Spain', 'Ismael Arilla / Juanjo Exposito', 'AV', NULL, false),
  ('Eldense', 'Spain 3', 'Spain', 'Victor Lafuente', 'PP / AV', NULL, false),
  ('Europa', 'Spain 3', 'Spain', 'Josep Maria Gene', 'AV', 'No estan empezando a valorar ningun jugador.', false),
  ('Guadalajara', 'Spain 3', 'Spain', 'Nestor Susaeta', 'PP', NULL, false),
  ('Hercules', 'Spain 3', 'Spain', 'Paco Peña', 'AV / AT', 'Ofrecidos: Aitor Manzanedo, Rica Funez, De Roa, Pau Calvo , Alberto Mari | Sin posiciones definidas, van a ser lentos en el mercado.', false),
  ('Ibiza', 'Spain 3', 'Spain', 'Javi Lara', 'AV', 'Ofrecidos: Carlos de Roa, Rica Funez, Miguel Mari, Vicente Esquerdo, Pedro Fidel, Carlos Jimenez | Tienen muy buenas referencias de Pedro Fidel y Miguel Mari.', false),
  ('Lugo', 'Spain 3', 'Spain', 'Javi Recio', 'AV', NULL, false),
  ('Marbella', 'Spain 3', 'Spain', NULL, NULL, NULL, false),
  ('Merida', 'Spain 3', 'Spain', 'Tiago Lenho / Tamas Balogh', 'PP', NULL, false),
  ('Mirandes', 'Spain 3', 'Spain', 'Alfredo Merino', 'BGF', NULL, false),
  ('Nastic', 'Spain 3', 'Spain', 'Sergi Pares', NULL, NULL, false),
  ('Ourense', 'Spain 3', 'Spain', 'Dario Cotelo', 'AV', 'Ofrecidos: Nacho Ramon | Interesados en incorporar un delantero grande.', false),
  ('Ponferradina', 'Spain 3', 'Spain', 'Jose Sietes', 'AV', 'Ofrecidos: Miguel Mari, Rica Funez, Aitor Manzanedo', false),
  ('Pontevedra', 'Spain 3', 'Spain', 'Jacobo Maestre', 'AV', 'Ofrecidos: Vicente Esquerdo | Tienen interes desde hace 2 ventanas', false),
  ('Racing Ferrol', 'Spain 3', 'Spain', 'Alex Vazquez', 'AV', 'Ofrecidos: Pablo Gozalbez,  Vicente Esquerdo, De Roa, Rica Funez, David Selles, Pablo Felipe | Me da largas con todo lo que no sea Vicente Esquerdo.', false),
  ('Real Aviles', 'Spain 3', 'Spain', 'Miguel Linares', 'AV / PP', NULL, false),
  ('Real Murcia', 'Spain 3', 'Spain', NULL, 'AV', NULL, false),
  ('Real Union', 'Spain 3', 'Spain', 'Mikel Bengoa', 'PP / AV', 'Ofrecidos: Aitor Manzanedo, Miguel Mari, Rica Funez, Carlos Jimenez, Pedro Fidel, Alex Cerda | Quieren a Alex, solo por el recuerdo de como estuvo, Miguel Mari interesa si es libre, y veran detenidamente a Aitor Manzanedo.', false),
  ('Sabadell', 'Spain 3', 'Spain', 'Lucas Viale', 'PP', NULL, false),
  ('Sanluqueño', 'Spain 3', 'Spain', 'Coke Andujar', 'BGF / AV', NULL, false),
  ('Sant Andreu', 'Spain 3', 'Spain', 'David Mordillo', 'NB', 'Ofrecidos: Rica, Pablo Felipe, Aitor, Pedro | Quieren a Rica y Pablo Felipe', false),
  ('Sevilla B', 'Spain 3', 'Spain', 'Agustin Lopez / Jose Ignacio', 'PP', NULL, false),
  ('Talavera', 'Spain 3', 'Spain', 'Toni Garcia / Carnicero', 'PP', NULL, false),
  ('Tarazona', 'Spain 3', 'Spain', 'Michel Sanz', 'AV', 'Ofrecidos: Aitor Manzanedo, Pau Calvo,  Pablo Felipe', false),
  ('Teruel', 'Spain 3', 'Spain', 'Juanra Cabrero', 'AV / NB', 'Ofrecidos: Pablo Felipe, De Roa, Rica, Pedro Fidel, Aitor', false),
  ('Torremolinos', 'Spain 3', 'Spain', 'Juan Gambero', 'AV', 'Bancarrota', false),
  ('Unionistas', 'Spain 3', 'Spain', 'Ivan Varela', 'NB', 'Ofrecidos: Rica, De Roa, Aitor, Pedro | Todas las posiciones', false),
  ('Villarreal B', 'Spain 3', 'Spain', 'De Cozar / David Karg', 'AV / LT', NULL, false),
  ('Zamora', 'Spain 3', 'Spain', 'David Vizcaino / Javier Pelaez', 'PP', NULL, false),
  ('Alaves B', 'Spain 3*', 'Spain', 'Sevillano / Raul Perez', 'PP / AV', NULL, false),
  ('Reus', 'Spain 3*', 'Spain', 'Albert Viñas', 'PP', NULL, false),
  ('Oviedo B', 'Spain 3*', 'Spain', 'Antonio Rivas', 'PP', NULL, false),
  ('Deportiva Minera', 'Spain 3*', 'Spain', 'Antonio Martinez', 'PP', NULL, false),
  ('Tenerife B', 'Spain 3*', 'Spain', 'Manu Guill', 'NB', NULL, false),
  ('Xerez', 'Spain 3*', 'Spain', 'Miguel Angel Rondan', NULL, 'Pendiente conseguir contacto', false),
  ('Utebo', 'Spain 3*', 'Spain', NULL, NULL, 'Pendiente conseguir contacto', false),
  ('UD Ourense', 'Spain 3*', 'Spain', 'Fernando Curras', NULL, 'Pendiente conseguir contacto', false),
  ('Toledano', 'Spain 3*', 'Spain', 'Paco Gallardo', NULL, 'Pendiente conseguir contacto', false),
  ('Terrassa', 'Spain 3*', 'Spain', 'Antonis Antoniou', NULL, 'Pendiente conseguir contacto', false),
  ('Sanse', 'Spain 3*', 'Spain', 'Jose Maria Groba', NULL, 'Pendiente conseguir contacto', false),
  ('Salamanca', 'Spain 3*', 'Spain', 'Carlos Valverde', NULL, 'Pendiente conseguir contacto', false),
  ('Recreativo Huelva', 'Spain 3*', 'Spain', 'Roberto Rios', NULL, 'Pendiente conseguir contacto', false),
  ('Rayo Majadahonda', 'Spain 3*', 'Spain', 'Cesar Gil', NULL, 'Pendiente conseguir contacto', false),
  ('Gimnastica Segoviana', 'Spain 3*', 'Spain', 'Joaquin Gomez Blasco', NULL, 'Pendiente conseguir contacto', false),
  ('Aguilas', 'Spain 3*', 'Spain', 'Pedro Reverte', NULL, 'Pendiente conseguir contacto', false),
  ('UD Logroñes', 'Spain 3*', 'Spain', 'Sergio Rodriguez', 'AV', NULL, false),
  ('UCAM Murcia', 'Spain 3*', 'Spain', 'Alvaro Muñoz', 'AV', NULL, false),
  ('Poblense', 'Spain 3*', 'Spain', 'Marti Munar', 'AV', NULL, false),
  ('Getafe B', 'Spain 3*', 'Spain', 'Manu Alcazar', 'AV', NULL, false),
  ('Coria', 'Spain 3*', 'Spain', 'Alfonso Gutierrez', 'AV', NULL, false),
  ('Conquense', 'Spain 3*', 'Spain', 'Cesar Navas', 'AV', NULL, false),
  ('Baleares', 'Spain 3*', 'Spain', 'Marc Julia', 'AV', NULL, false),
  ('Alcoyano', 'Spain 3*', 'Spain', 'Jose Alemany', 'AV', 'Ofrecidos: Pau Calvo, Aitor Manzanedo | Esperando respuestas', false),
  ('Osasuna', 'Spain 4', 'Spain', 'Cata / Braulio / Puñal', 'PP / LT', NULL, false),
  ('Arenteiro', 'Spain 4', 'Spain', NULL, 'AV', NULL, false),
  ('Zaragoza B', 'Spain 5', 'Spain', 'Quique García', 'AV', 'Ofrecidos: Pau Calvo', false),
  ('Albacete B', NULL, 'Spain', 'Victor Curto', 'AV', 'Ofrecidos: Pau Calvo', false)
ON CONFLICT DO NOTHING;
